// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package lendingv1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Params                                protoreflect.MessageDescriptor
	fd_Params_max_markets                    protoreflect.FieldDescriptor
	fd_Params_max_collateral_assets_per_user protoreflect.FieldDescriptor
	fd_Params_liquidation_enabled            protoreflect.FieldDescriptor
	fd_Params_oracle_staleness_limit         protoreflect.FieldDescriptor
	fd_Params_max_price_deviation            protoreflect.FieldDescriptor
	fd_Params_emergency_pause                protoreflect.FieldDescriptor
	fd_Params_oracle_enabled                 protoreflect.FieldDescriptor
)

func init() {
	file_overlend_lending_v1_params_proto_init()
	md_Params = File_overlend_lending_v1_params_proto.Messages().ByName("Params")
	fd_Params_max_markets = md_Params.Fields().ByName("max_markets")
	fd_Params_max_collateral_assets_per_user = md_Params.Fields().ByName("max_collateral_assets_per_user")
	fd_Params_liquidation_enabled = md_Params.Fields().ByName("liquidation_enabled")
	fd_Params_oracle_staleness_limit = md_Params.Fields().ByName("oracle_staleness_limit")
	fd_Params_max_price_deviation = md_Params.Fields().ByName("max_price_deviation")
	fd_Params_emergency_pause = md_Params.Fields().ByName("emergency_pause")
	fd_Params_oracle_enabled = md_Params.Fields().ByName("oracle_enabled")
}

var _ protoreflect.Message = (*fastReflection_Params)(nil)

type fastReflection_Params Params

func (x *Params) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Params)(x)
}

func (x *Params) slowProtoReflect() protoreflect.Message {
	mi := &file_overlend_lending_v1_params_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Params_messageType fastReflection_Params_messageType
var _ protoreflect.MessageType = fastReflection_Params_messageType{}

type fastReflection_Params_messageType struct{}

func (x fastReflection_Params_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Params)(nil)
}
func (x fastReflection_Params_messageType) New() protoreflect.Message {
	return new(fastReflection_Params)
}
func (x fastReflection_Params_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Params
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Params) Descriptor() protoreflect.MessageDescriptor {
	return md_Params
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Params) Type() protoreflect.MessageType {
	return _fastReflection_Params_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Params) New() protoreflect.Message {
	return new(fastReflection_Params)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Params) Interface() protoreflect.ProtoMessage {
	return (*Params)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Params) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.MaxMarkets != uint64(0) {
		value := protoreflect.ValueOfUint64(x.MaxMarkets)
		if !f(fd_Params_max_markets, value) {
			return
		}
	}
	if x.MaxCollateralAssetsPerUser != uint64(0) {
		value := protoreflect.ValueOfUint64(x.MaxCollateralAssetsPerUser)
		if !f(fd_Params_max_collateral_assets_per_user, value) {
			return
		}
	}
	if x.LiquidationEnabled != false {
		value := protoreflect.ValueOfBool(x.LiquidationEnabled)
		if !f(fd_Params_liquidation_enabled, value) {
			return
		}
	}
	if x.OracleStalenessLimit != "" {
		value := protoreflect.ValueOfString(x.OracleStalenessLimit)
		if !f(fd_Params_oracle_staleness_limit, value) {
			return
		}
	}
	if x.MaxPriceDeviation != "" {
		value := protoreflect.ValueOfString(x.MaxPriceDeviation)
		if !f(fd_Params_max_price_deviation, value) {
			return
		}
	}
	if x.EmergencyPause != false {
		value := protoreflect.ValueOfBool(x.EmergencyPause)
		if !f(fd_Params_emergency_pause, value) {
			return
		}
	}
	if x.OracleEnabled != false {
		value := protoreflect.ValueOfBool(x.OracleEnabled)
		if !f(fd_Params_oracle_enabled, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Params) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "overlend.lending.v1.Params.max_markets":
		return x.MaxMarkets != uint64(0)
	case "overlend.lending.v1.Params.max_collateral_assets_per_user":
		return x.MaxCollateralAssetsPerUser != uint64(0)
	case "overlend.lending.v1.Params.liquidation_enabled":
		return x.LiquidationEnabled != false
	case "overlend.lending.v1.Params.oracle_staleness_limit":
		return x.OracleStalenessLimit != ""
	case "overlend.lending.v1.Params.max_price_deviation":
		return x.MaxPriceDeviation != ""
	case "overlend.lending.v1.Params.emergency_pause":
		return x.EmergencyPause != false
	case "overlend.lending.v1.Params.oracle_enabled":
		return x.OracleEnabled != false
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: overlend.lending.v1.Params"))
		}
		panic(fmt.Errorf("message overlend.lending.v1.Params does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "overlend.lending.v1.Params.max_markets":
		x.MaxMarkets = uint64(0)
	case "overlend.lending.v1.Params.max_collateral_assets_per_user":
		x.MaxCollateralAssetsPerUser = uint64(0)
	case "overlend.lending.v1.Params.liquidation_enabled":
		x.LiquidationEnabled = false
	case "overlend.lending.v1.Params.oracle_staleness_limit":
		x.OracleStalenessLimit = ""
	case "overlend.lending.v1.Params.max_price_deviation":
		x.MaxPriceDeviation = ""
	case "overlend.lending.v1.Params.emergency_pause":
		x.EmergencyPause = false
	case "overlend.lending.v1.Params.oracle_enabled":
		x.OracleEnabled = false
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: overlend.lending.v1.Params"))
		}
		panic(fmt.Errorf("message overlend.lending.v1.Params does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Params) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "overlend.lending.v1.Params.max_markets":
		value := x.MaxMarkets
		return protoreflect.ValueOfUint64(value)
	case "overlend.lending.v1.Params.max_collateral_assets_per_user":
		value := x.MaxCollateralAssetsPerUser
		return protoreflect.ValueOfUint64(value)
	case "overlend.lending.v1.Params.liquidation_enabled":
		value := x.LiquidationEnabled
		return protoreflect.ValueOfBool(value)
	case "overlend.lending.v1.Params.oracle_staleness_limit":
		value := x.OracleStalenessLimit
		return protoreflect.ValueOfString(value)
	case "overlend.lending.v1.Params.max_price_deviation":
		value := x.MaxPriceDeviation
		return protoreflect.ValueOfString(value)
	case "overlend.lending.v1.Params.emergency_pause":
		value := x.EmergencyPause
		return protoreflect.ValueOfBool(value)
	case "overlend.lending.v1.Params.oracle_enabled":
		value := x.OracleEnabled
		return protoreflect.ValueOfBool(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: overlend.lending.v1.Params"))
		}
		panic(fmt.Errorf("message overlend.lending.v1.Params does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "overlend.lending.v1.Params.max_markets":
		x.MaxMarkets = value.Uint()
	case "overlend.lending.v1.Params.max_collateral_assets_per_user":
		x.MaxCollateralAssetsPerUser = value.Uint()
	case "overlend.lending.v1.Params.liquidation_enabled":
		x.LiquidationEnabled = value.Bool()
	case "overlend.lending.v1.Params.oracle_staleness_limit":
		x.OracleStalenessLimit = value.Interface().(string)
	case "overlend.lending.v1.Params.max_price_deviation":
		x.MaxPriceDeviation = value.Interface().(string)
	case "overlend.lending.v1.Params.emergency_pause":
		x.EmergencyPause = value.Bool()
	case "overlend.lending.v1.Params.oracle_enabled":
		x.OracleEnabled = value.Bool()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: overlend.lending.v1.Params"))
		}
		panic(fmt.Errorf("message overlend.lending.v1.Params does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "overlend.lending.v1.Params.max_markets":
		panic(fmt.Errorf("field max_markets of message overlend.lending.v1.Params is not mutable"))
	case "overlend.lending.v1.Params.max_collateral_assets_per_user":
		panic(fmt.Errorf("field max_collateral_assets_per_user of message overlend.lending.v1.Params is not mutable"))
	case "overlend.lending.v1.Params.liquidation_enabled":
		panic(fmt.Errorf("field liquidation_enabled of message overlend.lending.v1.Params is not mutable"))
	case "overlend.lending.v1.Params.oracle_staleness_limit":
		panic(fmt.Errorf("field oracle_staleness_limit of message overlend.lending.v1.Params is not mutable"))
	case "overlend.lending.v1.Params.max_price_deviation":
		panic(fmt.Errorf("field max_price_deviation of message overlend.lending.v1.Params is not mutable"))
	case "overlend.lending.v1.Params.emergency_pause":
		panic(fmt.Errorf("field emergency_pause of message overlend.lending.v1.Params is not mutable"))
	case "overlend.lending.v1.Params.oracle_enabled":
		panic(fmt.Errorf("field oracle_enabled of message overlend.lending.v1.Params is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: overlend.lending.v1.Params"))
		}
		panic(fmt.Errorf("message overlend.lending.v1.Params does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Params) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "overlend.lending.v1.Params.max_markets":
		return protoreflect.ValueOfUint64(uint64(0))
	case "overlend.lending.v1.Params.max_collateral_assets_per_user":
		return protoreflect.ValueOfUint64(uint64(0))
	case "overlend.lending.v1.Params.liquidation_enabled":
		return protoreflect.ValueOfBool(false)
	case "overlend.lending.v1.Params.oracle_staleness_limit":
		return protoreflect.ValueOfString("")
	case "overlend.lending.v1.Params.max_price_deviation":
		return protoreflect.ValueOfString("")
	case "overlend.lending.v1.Params.emergency_pause":
		return protoreflect.ValueOfBool(false)
	case "overlend.lending.v1.Params.oracle_enabled":
		return protoreflect.ValueOfBool(false)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: overlend.lending.v1.Params"))
		}
		panic(fmt.Errorf("message overlend.lending.v1.Params does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Params) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in overlend.lending.v1.Params", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Params) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Params) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Params) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Params)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.MaxMarkets != 0 {
			n += 1 + runtime.Sov(uint64(x.MaxMarkets))
		}
		if x.MaxCollateralAssetsPerUser != 0 {
			n += 1 + runtime.Sov(uint64(x.MaxCollateralAssetsPerUser))
		}
		if x.LiquidationEnabled {
			n += 2
		}
		l = len(x.OracleStalenessLimit)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MaxPriceDeviation)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.EmergencyPause {
			n += 2
		}
		if x.OracleEnabled {
			n += 2
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Params)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.OracleEnabled {
			i--
			if x.OracleEnabled {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x38
		}
		if x.EmergencyPause {
			i--
			if x.EmergencyPause {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x30
		}
		if len(x.MaxPriceDeviation) > 0 {
			i -= len(x.MaxPriceDeviation)
			copy(dAtA[i:], x.MaxPriceDeviation)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MaxPriceDeviation)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.OracleStalenessLimit) > 0 {
			i -= len(x.OracleStalenessLimit)
			copy(dAtA[i:], x.OracleStalenessLimit)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OracleStalenessLimit)))
			i--
			dAtA[i] = 0x22
		}
		if x.LiquidationEnabled {
			i--
			if x.LiquidationEnabled {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x18
		}
		if x.MaxCollateralAssetsPerUser != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.MaxCollateralAssetsPerUser))
			i--
			dAtA[i] = 0x10
		}
		if x.MaxMarkets != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.MaxMarkets))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Params)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Params: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MaxMarkets", wireType)
				}
				x.MaxMarkets = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.MaxMarkets |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MaxCollateralAssetsPerUser", wireType)
				}
				x.MaxCollateralAssetsPerUser = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.MaxCollateralAssetsPerUser |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LiquidationEnabled", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.LiquidationEnabled = bool(v != 0)
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OracleStalenessLimit", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OracleStalenessLimit = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MaxPriceDeviation", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MaxPriceDeviation = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EmergencyPause", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.EmergencyPause = bool(v != 0)
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OracleEnabled", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.OracleEnabled = bool(v != 0)
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: overlend/lending/v1/params.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Params defines global module parameters
type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// jumlah maksimal market yang boleh ada di sistem
	MaxMarkets uint64 `protobuf:"varint,1,opt,name=max_markets,json=maxMarkets,proto3" json:"max_markets,omitempty"`
	// maksimal jumlah jenis collateral per user
	MaxCollateralAssetsPerUser uint64 `protobuf:"varint,2,opt,name=max_collateral_assets_per_user,json=maxCollateralAssetsPerUser,proto3" json:"max_collateral_assets_per_user,omitempty"`
	// apakah fitur likuidasi aktif
	LiquidationEnabled bool `protobuf:"varint,3,opt,name=liquidation_enabled,json=liquidationEnabled,proto3" json:"liquidation_enabled,omitempty"`
	// batas global umur data harga
	OracleStalenessLimit string `protobuf:"bytes,4,opt,name=oracle_staleness_limit,json=oracleStalenessLimit,proto3" json:"oracle_staleness_limit,omitempty"`
	// batas selisih harga maksimum yang diterima
	MaxPriceDeviation string `protobuf:"bytes,5,opt,name=max_price_deviation,json=maxPriceDeviation,proto3" json:"max_price_deviation,omitempty"`
	// kill switch seluruh protocol
	EmergencyPause bool `protobuf:"varint,6,opt,name=emergency_pause,json=emergencyPause,proto3" json:"emergency_pause,omitempty"`
	// apakah oracle aktif
	OracleEnabled bool `protobuf:"varint,7,opt,name=oracle_enabled,json=oracleEnabled,proto3" json:"oracle_enabled,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overlend_lending_v1_params_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_overlend_lending_v1_params_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetMaxMarkets() uint64 {
	if x != nil {
		return x.MaxMarkets
	}
	return 0
}

func (x *Params) GetMaxCollateralAssetsPerUser() uint64 {
	if x != nil {
		return x.MaxCollateralAssetsPerUser
	}
	return 0
}

func (x *Params) GetLiquidationEnabled() bool {
	if x != nil {
		return x.LiquidationEnabled
	}
	return false
}

func (x *Params) GetOracleStalenessLimit() string {
	if x != nil {
		return x.OracleStalenessLimit
	}
	return ""
}

func (x *Params) GetMaxPriceDeviation() string {
	if x != nil {
		return x.MaxPriceDeviation
	}
	return ""
}

func (x *Params) GetEmergencyPause() bool {
	if x != nil {
		return x.EmergencyPause
	}
	return false
}

func (x *Params) GetOracleEnabled() bool {
	if x != nil {
		return x.OracleEnabled
	}
	return false
}

var File_overlend_lending_v1_params_proto protoreflect.FileDescriptor

var file_overlend_lending_v1_params_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x2f, 0x6c, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x13, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x6c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x03, 0x0a, 0x06, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x73, 0x12, 0x42, 0x0a, 0x1e, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x6c, 0x6c,
	0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x5f, 0x70, 0x65,
	0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x1a, 0x6d, 0x61,
	0x78, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x50, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x13, 0x6c, 0x69, 0x71, 0x75,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x4f, 0x0a, 0x16, 0x6f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x19, 0xda, 0xde, 0x1f, 0x15, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68,
	0x2e, 0x49, 0x6e, 0x74, 0x52, 0x14, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x6c,
	0x65, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x4f, 0x0a, 0x13, 0x6d, 0x61,
	0x78, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1f, 0xda, 0xde, 0x1f, 0x1b, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x4c,
	0x65, 0x67, 0x61, 0x63, 0x79, 0x44, 0x65, 0x63, 0x52, 0x11, 0x6d, 0x61, 0x78, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x44, 0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x65,
	0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x70, 0x61, 0x75, 0x73, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x65, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x50,
	0x61, 0x75, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x5f, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6f, 0x72,
	0x61, 0x63, 0x6c, 0x65, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x42, 0xde, 0x01, 0x0a, 0x17,
	0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x6c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2d, 0x75, 0x6e, 0x69,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x2f, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x2f, 0x6c, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x76, 0x31,
	0xa2, 0x02, 0x03, 0x4f, 0x4c, 0x58, 0xaa, 0x02, 0x13, 0x4f, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x6e,
	0x64, 0x2e, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x13, 0x4f,
	0x76, 0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x5c, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5c,
	0x56, 0x31, 0xe2, 0x02, 0x1f, 0x4f, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x5c, 0x4c, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x15, 0x4f, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x3a,
	0x3a, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_overlend_lending_v1_params_proto_rawDescOnce sync.Once
	file_overlend_lending_v1_params_proto_rawDescData = file_overlend_lending_v1_params_proto_rawDesc
)

func file_overlend_lending_v1_params_proto_rawDescGZIP() []byte {
	file_overlend_lending_v1_params_proto_rawDescOnce.Do(func() {
		file_overlend_lending_v1_params_proto_rawDescData = protoimpl.X.CompressGZIP(file_overlend_lending_v1_params_proto_rawDescData)
	})
	return file_overlend_lending_v1_params_proto_rawDescData
}

var file_overlend_lending_v1_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_overlend_lending_v1_params_proto_goTypes = []interface{}{
	(*Params)(nil), // 0: overlend.lending.v1.Params
}
var file_overlend_lending_v1_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_overlend_lending_v1_params_proto_init() }
func file_overlend_lending_v1_params_proto_init() {
	if File_overlend_lending_v1_params_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_overlend_lending_v1_params_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_overlend_lending_v1_params_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_overlend_lending_v1_params_proto_goTypes,
		DependencyIndexes: file_overlend_lending_v1_params_proto_depIdxs,
		MessageInfos:      file_overlend_lending_v1_params_proto_msgTypes,
	}.Build()
	File_overlend_lending_v1_params_proto = out.File
	file_overlend_lending_v1_params_proto_rawDesc = nil
	file_overlend_lending_v1_params_proto_goTypes = nil
	file_overlend_lending_v1_params_proto_depIdxs = nil
}
