// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: overlend/lending/v1/query.proto

package lendingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Params_FullMethodName          = "/overlend.lending.v1.Query/Params"
	Query_Market_FullMethodName          = "/overlend.lending.v1.Query/Market"
	Query_Markets_FullMethodName         = "/overlend.lending.v1.Query/Markets"
	Query_UserCollateral_FullMethodName  = "/overlend.lending.v1.Query/UserCollateral"
	Query_UserCollaterals_FullMethodName = "/overlend.lending.v1.Query/UserCollaterals"
	Query_UserDebt_FullMethodName        = "/overlend.lending.v1.Query/UserDebt"
	Query_UserDebts_FullMethodName       = "/overlend.lending.v1.Query/UserDebts"
	Query_UserPosition_FullMethodName    = "/overlend.lending.v1.Query/UserPosition"
	Query_MarketState_FullMethodName     = "/overlend.lending.v1.Query/MarketState"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query, read-only API (gRPC + REST) untuk ambil data dari blockchain
type QueryClient interface {
	// Params, ambil global config module
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Market, ambil 1 market by denom
	Market(ctx context.Context, in *QueryMarketRequest, opts ...grpc.CallOption) (*QueryMarketResponse, error)
	// Markets, ambil semua market (dengan pagination)
	Markets(ctx context.Context, in *QueryMarketsRequest, opts ...grpc.CallOption) (*QueryMarketsResponse, error)
	// UserCollateral, ambil collateral user untuk 1 aset
	UserCollateral(ctx context.Context, in *QueryUserCollateralRequest, opts ...grpc.CallOption) (*QueryUserCollateralResponse, error)
	// UserCollaterals, ambil semua collateral user
	UserCollaterals(ctx context.Context, in *QueryUserCollateralsRequest, opts ...grpc.CallOption) (*QueryUserCollateralsResponse, error)
	// UserDebt, ambil utang user untuk 1 aset
	UserDebt(ctx context.Context, in *QueryUserDebtRequest, opts ...grpc.CallOption) (*QueryUserDebtResponse, error)
	// UserDebts, ambil semua utang user
	UserDebts(ctx context.Context, in *QueryUserDebtsRequest, opts ...grpc.CallOption) (*QueryUserDebtsResponse, error)
	// UserPosition, ambil posisi finansial user secara agregat
	UserPosition(ctx context.Context, in *QueryUserPositionRequest, opts ...grpc.CallOption) (*QueryUserPositionResponse, error)
	// MarketState, ambil state runtime market
	MarketState(ctx context.Context, in *QueryMarketStateRequest, opts ...grpc.CallOption) (*QueryMarketStateResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Market(ctx context.Context, in *QueryMarketRequest, opts ...grpc.CallOption) (*QueryMarketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMarketResponse)
	err := c.cc.Invoke(ctx, Query_Market_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Markets(ctx context.Context, in *QueryMarketsRequest, opts ...grpc.CallOption) (*QueryMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMarketsResponse)
	err := c.cc.Invoke(ctx, Query_Markets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserCollateral(ctx context.Context, in *QueryUserCollateralRequest, opts ...grpc.CallOption) (*QueryUserCollateralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserCollateralResponse)
	err := c.cc.Invoke(ctx, Query_UserCollateral_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserCollaterals(ctx context.Context, in *QueryUserCollateralsRequest, opts ...grpc.CallOption) (*QueryUserCollateralsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserCollateralsResponse)
	err := c.cc.Invoke(ctx, Query_UserCollaterals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserDebt(ctx context.Context, in *QueryUserDebtRequest, opts ...grpc.CallOption) (*QueryUserDebtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserDebtResponse)
	err := c.cc.Invoke(ctx, Query_UserDebt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserDebts(ctx context.Context, in *QueryUserDebtsRequest, opts ...grpc.CallOption) (*QueryUserDebtsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserDebtsResponse)
	err := c.cc.Invoke(ctx, Query_UserDebts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserPosition(ctx context.Context, in *QueryUserPositionRequest, opts ...grpc.CallOption) (*QueryUserPositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserPositionResponse)
	err := c.cc.Invoke(ctx, Query_UserPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MarketState(ctx context.Context, in *QueryMarketStateRequest, opts ...grpc.CallOption) (*QueryMarketStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMarketStateResponse)
	err := c.cc.Invoke(ctx, Query_MarketState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query, read-only API (gRPC + REST) untuk ambil data dari blockchain
type QueryServer interface {
	// Params, ambil global config module
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Market, ambil 1 market by denom
	Market(context.Context, *QueryMarketRequest) (*QueryMarketResponse, error)
	// Markets, ambil semua market (dengan pagination)
	Markets(context.Context, *QueryMarketsRequest) (*QueryMarketsResponse, error)
	// UserCollateral, ambil collateral user untuk 1 aset
	UserCollateral(context.Context, *QueryUserCollateralRequest) (*QueryUserCollateralResponse, error)
	// UserCollaterals, ambil semua collateral user
	UserCollaterals(context.Context, *QueryUserCollateralsRequest) (*QueryUserCollateralsResponse, error)
	// UserDebt, ambil utang user untuk 1 aset
	UserDebt(context.Context, *QueryUserDebtRequest) (*QueryUserDebtResponse, error)
	// UserDebts, ambil semua utang user
	UserDebts(context.Context, *QueryUserDebtsRequest) (*QueryUserDebtsResponse, error)
	// UserPosition, ambil posisi finansial user secara agregat
	UserPosition(context.Context, *QueryUserPositionRequest) (*QueryUserPositionResponse, error)
	// MarketState, ambil state runtime market
	MarketState(context.Context, *QueryMarketStateRequest) (*QueryMarketStateResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Market(context.Context, *QueryMarketRequest) (*QueryMarketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Market not implemented")
}
func (UnimplementedQueryServer) Markets(context.Context, *QueryMarketsRequest) (*QueryMarketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Markets not implemented")
}
func (UnimplementedQueryServer) UserCollateral(context.Context, *QueryUserCollateralRequest) (*QueryUserCollateralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCollateral not implemented")
}
func (UnimplementedQueryServer) UserCollaterals(context.Context, *QueryUserCollateralsRequest) (*QueryUserCollateralsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCollaterals not implemented")
}
func (UnimplementedQueryServer) UserDebt(context.Context, *QueryUserDebtRequest) (*QueryUserDebtResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserDebt not implemented")
}
func (UnimplementedQueryServer) UserDebts(context.Context, *QueryUserDebtsRequest) (*QueryUserDebtsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserDebts not implemented")
}
func (UnimplementedQueryServer) UserPosition(context.Context, *QueryUserPositionRequest) (*QueryUserPositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserPosition not implemented")
}
func (UnimplementedQueryServer) MarketState(context.Context, *QueryMarketStateRequest) (*QueryMarketStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarketState not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Market_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Market(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Market_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Market(ctx, req.(*QueryMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Markets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Markets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Markets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Markets(ctx, req.(*QueryMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserCollateral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserCollateralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserCollateral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_UserCollateral_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserCollateral(ctx, req.(*QueryUserCollateralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserCollaterals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserCollateralsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserCollaterals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_UserCollaterals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserCollaterals(ctx, req.(*QueryUserCollateralsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserDebt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserDebtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserDebt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_UserDebt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserDebt(ctx, req.(*QueryUserDebtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserDebts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserDebtsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserDebts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_UserDebts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserDebts(ctx, req.(*QueryUserDebtsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_UserPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserPosition(ctx, req.(*QueryUserPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MarketState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMarketStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MarketState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_MarketState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MarketState(ctx, req.(*QueryMarketStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "overlend.lending.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Market",
			Handler:    _Query_Market_Handler,
		},
		{
			MethodName: "Markets",
			Handler:    _Query_Markets_Handler,
		},
		{
			MethodName: "UserCollateral",
			Handler:    _Query_UserCollateral_Handler,
		},
		{
			MethodName: "UserCollaterals",
			Handler:    _Query_UserCollaterals_Handler,
		},
		{
			MethodName: "UserDebt",
			Handler:    _Query_UserDebt_Handler,
		},
		{
			MethodName: "UserDebts",
			Handler:    _Query_UserDebts_Handler,
		},
		{
			MethodName: "UserPosition",
			Handler:    _Query_UserPosition_Handler,
		},
		{
			MethodName: "MarketState",
			Handler:    _Query_MarketState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "overlend/lending/v1/query.proto",
}
