// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: overlend/lending/v1/event.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventParamsUpdated diemit saat params diupdate
type EventParamsUpdated struct {
	MaxMarkets                 uint64                       `protobuf:"varint,1,opt,name=max_markets,json=maxMarkets,proto3" json:"max_markets,omitempty"`
	MaxCollateralAssetsPerUser uint64                       `protobuf:"varint,2,opt,name=max_collateral_assets_per_user,json=maxCollateralAssetsPerUser,proto3" json:"max_collateral_assets_per_user,omitempty"`
	LiquidationEnabled         bool                         `protobuf:"varint,3,opt,name=liquidation_enabled,json=liquidationEnabled,proto3" json:"liquidation_enabled,omitempty"`
	OracleStalenessLimit       *cosmossdk_io_math.Int       `protobuf:"bytes,4,opt,name=oracle_staleness_limit,json=oracleStalenessLimit,proto3,customtype=cosmossdk.io/math.Int" json:"oracle_staleness_limit,omitempty"`
	MaxPriceDeviation          *cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=max_price_deviation,json=maxPriceDeviation,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"max_price_deviation,omitempty"`
	EmergencyPause             bool                         `protobuf:"varint,6,opt,name=emergency_pause,json=emergencyPause,proto3" json:"emergency_pause,omitempty"`
	OracleEnabled              bool                         `protobuf:"varint,7,opt,name=oracle_enabled,json=oracleEnabled,proto3" json:"oracle_enabled,omitempty"`
}

func (m *EventParamsUpdated) Reset()         { *m = EventParamsUpdated{} }
func (m *EventParamsUpdated) String() string { return proto.CompactTextString(m) }
func (*EventParamsUpdated) ProtoMessage()    {}
func (*EventParamsUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_a734d7d4abce5e36, []int{0}
}
func (m *EventParamsUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventParamsUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventParamsUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventParamsUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventParamsUpdated.Merge(m, src)
}
func (m *EventParamsUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EventParamsUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventParamsUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventParamsUpdated proto.InternalMessageInfo

func (m *EventParamsUpdated) GetMaxMarkets() uint64 {
	if m != nil {
		return m.MaxMarkets
	}
	return 0
}

func (m *EventParamsUpdated) GetMaxCollateralAssetsPerUser() uint64 {
	if m != nil {
		return m.MaxCollateralAssetsPerUser
	}
	return 0
}

func (m *EventParamsUpdated) GetLiquidationEnabled() bool {
	if m != nil {
		return m.LiquidationEnabled
	}
	return false
}

func (m *EventParamsUpdated) GetEmergencyPause() bool {
	if m != nil {
		return m.EmergencyPause
	}
	return false
}

func (m *EventParamsUpdated) GetOracleEnabled() bool {
	if m != nil {
		return m.OracleEnabled
	}
	return false
}

// EventDepositCollateral diemit saat user setor collateral
type EventDepositCollateral struct {
	Sender string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Denom  string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount *cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount,omitempty"`
}

func (m *EventDepositCollateral) Reset()         { *m = EventDepositCollateral{} }
func (m *EventDepositCollateral) String() string { return proto.CompactTextString(m) }
func (*EventDepositCollateral) ProtoMessage()    {}
func (*EventDepositCollateral) Descriptor() ([]byte, []int) {
	return fileDescriptor_a734d7d4abce5e36, []int{1}
}
func (m *EventDepositCollateral) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDepositCollateral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDepositCollateral.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDepositCollateral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDepositCollateral.Merge(m, src)
}
func (m *EventDepositCollateral) XXX_Size() int {
	return m.Size()
}
func (m *EventDepositCollateral) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDepositCollateral.DiscardUnknown(m)
}

var xxx_messageInfo_EventDepositCollateral proto.InternalMessageInfo

func (m *EventDepositCollateral) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *EventDepositCollateral) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// EventDepositCollateral diemit saat user tarik collateral
type EventWithdrawCollateral struct {
	Sender string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Denom  string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount *cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount,omitempty"`
}

func (m *EventWithdrawCollateral) Reset()         { *m = EventWithdrawCollateral{} }
func (m *EventWithdrawCollateral) String() string { return proto.CompactTextString(m) }
func (*EventWithdrawCollateral) ProtoMessage()    {}
func (*EventWithdrawCollateral) Descriptor() ([]byte, []int) {
	return fileDescriptor_a734d7d4abce5e36, []int{2}
}
func (m *EventWithdrawCollateral) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventWithdrawCollateral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventWithdrawCollateral.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventWithdrawCollateral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventWithdrawCollateral.Merge(m, src)
}
func (m *EventWithdrawCollateral) XXX_Size() int {
	return m.Size()
}
func (m *EventWithdrawCollateral) XXX_DiscardUnknown() {
	xxx_messageInfo_EventWithdrawCollateral.DiscardUnknown(m)
}

var xxx_messageInfo_EventWithdrawCollateral proto.InternalMessageInfo

func (m *EventWithdrawCollateral) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *EventWithdrawCollateral) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// EventBorrow diemit saat user meminjam asset
type EventBorrow struct {
	Borrower string                 `protobuf:"bytes,1,opt,name=borrower,proto3" json:"borrower,omitempty"`
	Denom    string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount   *cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount,omitempty"`
	// total utang terupdate setelah peminjaman
	NewTotalDebt *cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=new_total_debt,json=newTotalDebt,proto3,customtype=cosmossdk.io/math.Int" json:"new_total_debt,omitempty"`
}

func (m *EventBorrow) Reset()         { *m = EventBorrow{} }
func (m *EventBorrow) String() string { return proto.CompactTextString(m) }
func (*EventBorrow) ProtoMessage()    {}
func (*EventBorrow) Descriptor() ([]byte, []int) {
	return fileDescriptor_a734d7d4abce5e36, []int{3}
}
func (m *EventBorrow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBorrow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBorrow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBorrow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBorrow.Merge(m, src)
}
func (m *EventBorrow) XXX_Size() int {
	return m.Size()
}
func (m *EventBorrow) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBorrow.DiscardUnknown(m)
}

var xxx_messageInfo_EventBorrow proto.InternalMessageInfo

func (m *EventBorrow) GetBorrower() string {
	if m != nil {
		return m.Borrower
	}
	return ""
}

func (m *EventBorrow) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// EventRepay diemit saat user repays debt
type EventRepay struct {
	Borrower string                 `protobuf:"bytes,1,opt,name=borrower,proto3" json:"borrower,omitempty"`
	Denom    string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount   *cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount,omitempty"`
	// total utang terupdate setelah repay
	RemainingDebt *cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=remaining_debt,json=remainingDebt,proto3,customtype=cosmossdk.io/math.Int" json:"remaining_debt,omitempty"`
}

func (m *EventRepay) Reset()         { *m = EventRepay{} }
func (m *EventRepay) String() string { return proto.CompactTextString(m) }
func (*EventRepay) ProtoMessage()    {}
func (*EventRepay) Descriptor() ([]byte, []int) {
	return fileDescriptor_a734d7d4abce5e36, []int{4}
}
func (m *EventRepay) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRepay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRepay.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRepay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRepay.Merge(m, src)
}
func (m *EventRepay) XXX_Size() int {
	return m.Size()
}
func (m *EventRepay) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRepay.DiscardUnknown(m)
}

var xxx_messageInfo_EventRepay proto.InternalMessageInfo

func (m *EventRepay) GetBorrower() string {
	if m != nil {
		return m.Borrower
	}
	return ""
}

func (m *EventRepay) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// EventLiquidate diemit saat likuidasi terjadi
type EventLiquidate struct {
	Liquidator       string                 `protobuf:"bytes,1,opt,name=liquidator,proto3" json:"liquidator,omitempty"`
	Borrower         string                 `protobuf:"bytes,2,opt,name=borrower,proto3" json:"borrower,omitempty"`
	RepayDenom       string                 `protobuf:"bytes,3,opt,name=repay_denom,json=repayDenom,proto3" json:"repay_denom,omitempty"`
	CollateralDenom  string                 `protobuf:"bytes,4,opt,name=collateral_denom,json=collateralDenom,proto3" json:"collateral_denom,omitempty"`
	RepayAmount      *cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=repay_amount,json=repayAmount,proto3,customtype=cosmossdk.io/math.Int" json:"repay_amount,omitempty"`
	CollateralSeized *cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=collateral_seized,json=collateralSeized,proto3,customtype=cosmossdk.io/math.Int" json:"collateral_seized,omitempty"`
	// protocol biaya opsional yang diambil
	ProtocolFee *cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=protocol_fee,json=protocolFee,proto3,customtype=cosmossdk.io/math.Int" json:"protocol_fee,omitempty"`
}

func (m *EventLiquidate) Reset()         { *m = EventLiquidate{} }
func (m *EventLiquidate) String() string { return proto.CompactTextString(m) }
func (*EventLiquidate) ProtoMessage()    {}
func (*EventLiquidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a734d7d4abce5e36, []int{5}
}
func (m *EventLiquidate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventLiquidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventLiquidate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventLiquidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLiquidate.Merge(m, src)
}
func (m *EventLiquidate) XXX_Size() int {
	return m.Size()
}
func (m *EventLiquidate) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLiquidate.DiscardUnknown(m)
}

var xxx_messageInfo_EventLiquidate proto.InternalMessageInfo

func (m *EventLiquidate) GetLiquidator() string {
	if m != nil {
		return m.Liquidator
	}
	return ""
}

func (m *EventLiquidate) GetBorrower() string {
	if m != nil {
		return m.Borrower
	}
	return ""
}

func (m *EventLiquidate) GetRepayDenom() string {
	if m != nil {
		return m.RepayDenom
	}
	return ""
}

func (m *EventLiquidate) GetCollateralDenom() string {
	if m != nil {
		return m.CollateralDenom
	}
	return ""
}

// EventMarketUpdated diemit saat market config changes
type EventMarketUpdated struct {
	Denom                string                       `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Ltv                  *cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=ltv,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"ltv,omitempty"`
	LiquidationThreshold *cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=liquidation_threshold,json=liquidationThreshold,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"liquidation_threshold,omitempty"`
	LiquidationBonus     *cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=liquidation_bonus,json=liquidationBonus,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"liquidation_bonus,omitempty"`
	ReserveFactor        *cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=reserve_factor,json=reserveFactor,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"reserve_factor,omitempty"`
	CloseFactor          *cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=close_factor,json=closeFactor,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"close_factor,omitempty"`
	IsEnabled            bool                         `protobuf:"varint,7,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	BorrowCap            *cosmossdk_io_math.Int       `protobuf:"bytes,8,opt,name=borrow_cap,json=borrowCap,proto3,customtype=cosmossdk.io/math.Int" json:"borrow_cap,omitempty"`
	SupplyCap            *cosmossdk_io_math.Int       `protobuf:"bytes,9,opt,name=supply_cap,json=supplyCap,proto3,customtype=cosmossdk.io/math.Int" json:"supply_cap,omitempty"`
	RiskTier             uint32                       `protobuf:"varint,10,opt,name=risk_tier,json=riskTier,proto3" json:"risk_tier,omitempty"`
}

func (m *EventMarketUpdated) Reset()         { *m = EventMarketUpdated{} }
func (m *EventMarketUpdated) String() string { return proto.CompactTextString(m) }
func (*EventMarketUpdated) ProtoMessage()    {}
func (*EventMarketUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_a734d7d4abce5e36, []int{6}
}
func (m *EventMarketUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMarketUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMarketUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMarketUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMarketUpdated.Merge(m, src)
}
func (m *EventMarketUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EventMarketUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMarketUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventMarketUpdated proto.InternalMessageInfo

func (m *EventMarketUpdated) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *EventMarketUpdated) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

func (m *EventMarketUpdated) GetRiskTier() uint32 {
	if m != nil {
		return m.RiskTier
	}
	return 0
}

// EventInterestAccrued diemit saat index bunga terupdate
type EventInterestAccrued struct {
	Denom       string                       `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	BorrowIndex *cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=borrow_index,json=borrowIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"borrow_index,omitempty"`
	SupplyIndex *cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=supply_index,json=supplyIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"supply_index,omitempty"`
	BlockHeight int64                        `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *EventInterestAccrued) Reset()         { *m = EventInterestAccrued{} }
func (m *EventInterestAccrued) String() string { return proto.CompactTextString(m) }
func (*EventInterestAccrued) ProtoMessage()    {}
func (*EventInterestAccrued) Descriptor() ([]byte, []int) {
	return fileDescriptor_a734d7d4abce5e36, []int{7}
}
func (m *EventInterestAccrued) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventInterestAccrued) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventInterestAccrued.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventInterestAccrued) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventInterestAccrued.Merge(m, src)
}
func (m *EventInterestAccrued) XXX_Size() int {
	return m.Size()
}
func (m *EventInterestAccrued) XXX_DiscardUnknown() {
	xxx_messageInfo_EventInterestAccrued.DiscardUnknown(m)
}

var xxx_messageInfo_EventInterestAccrued proto.InternalMessageInfo

func (m *EventInterestAccrued) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *EventInterestAccrued) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*EventParamsUpdated)(nil), "overlend.lending.v1.EventParamsUpdated")
	proto.RegisterType((*EventDepositCollateral)(nil), "overlend.lending.v1.EventDepositCollateral")
	proto.RegisterType((*EventWithdrawCollateral)(nil), "overlend.lending.v1.EventWithdrawCollateral")
	proto.RegisterType((*EventBorrow)(nil), "overlend.lending.v1.EventBorrow")
	proto.RegisterType((*EventRepay)(nil), "overlend.lending.v1.EventRepay")
	proto.RegisterType((*EventLiquidate)(nil), "overlend.lending.v1.EventLiquidate")
	proto.RegisterType((*EventMarketUpdated)(nil), "overlend.lending.v1.EventMarketUpdated")
	proto.RegisterType((*EventInterestAccrued)(nil), "overlend.lending.v1.EventInterestAccrued")
}

func init() { proto.RegisterFile("overlend/lending/v1/event.proto", fileDescriptor_a734d7d4abce5e36) }

var fileDescriptor_a734d7d4abce5e36 = []byte{
	// 953 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0xd6, 0x89, 0x89, 0x9f, 0x1d, 0xb7, 0x99, 0xb8, 0xc5, 0x4d, 0x85, 0x1d, 0x2c, 0x21,
	0xc2, 0xa1, 0x36, 0x11, 0x08, 0xf5, 0x80, 0x04, 0x71, 0xdd, 0x88, 0x48, 0x41, 0xb5, 0x36, 0xa9,
	0x90, 0xb8, 0xac, 0xc6, 0xbb, 0xaf, 0xeb, 0x51, 0x76, 0x67, 0x96, 0x99, 0xb1, 0x63, 0xf3, 0x2b,
	0x2a, 0xc1, 0x91, 0x9f, 0xc1, 0x95, 0x3b, 0x17, 0xa4, 0x8a, 0x0b, 0xa8, 0x87, 0x0a, 0x25, 0x7f,
	0x04, 0xcd, 0xcc, 0xda, 0x75, 0x40, 0xc4, 0x3e, 0x20, 0xc1, 0xc5, 0xf2, 0xbe, 0xf9, 0xbe, 0x6f,
	0xdf, 0xf7, 0xe6, 0xcd, 0xdb, 0x81, 0xa6, 0x18, 0xa3, 0x4c, 0x90, 0x47, 0x1d, 0xf3, 0xc3, 0x78,
	0xdc, 0x19, 0x1f, 0x74, 0x70, 0x8c, 0x5c, 0xb7, 0x33, 0x29, 0xb4, 0x20, 0x3b, 0x33, 0x40, 0x3b,
	0x07, 0xb4, 0xc7, 0x07, 0xbb, 0xb5, 0x58, 0xc4, 0xc2, 0xae, 0x77, 0xcc, 0x3f, 0x07, 0xdd, 0xbd,
	0x1f, 0x0a, 0x95, 0x0a, 0x15, 0xb8, 0x05, 0xf7, 0xe0, 0x96, 0x5a, 0x3f, 0x14, 0x80, 0x3c, 0x31,
	0xaa, 0x7d, 0x2a, 0x69, 0xaa, 0x9e, 0x65, 0x11, 0xd5, 0x18, 0x91, 0x26, 0x94, 0x53, 0x3a, 0x09,
	0x52, 0x2a, 0xcf, 0x51, 0xab, 0xba, 0xb7, 0xe7, 0xed, 0xaf, 0xfb, 0x90, 0xd2, 0xc9, 0x97, 0x2e,
	0x42, 0xba, 0xd0, 0x30, 0x80, 0x50, 0x24, 0x09, 0xd5, 0x28, 0x69, 0x12, 0x50, 0xa5, 0x50, 0xab,
	0x20, 0x43, 0x19, 0x8c, 0x14, 0xca, 0xfa, 0x2d, 0xcb, 0xd9, 0x4d, 0xe9, 0xe4, 0xf1, 0x1c, 0x74,
	0x68, 0x31, 0x7d, 0x94, 0xcf, 0x14, 0x4a, 0xd2, 0x81, 0x9d, 0x84, 0x7d, 0x33, 0x62, 0x11, 0xd5,
	0x4c, 0xf0, 0x00, 0x39, 0x1d, 0x24, 0x18, 0xd5, 0x0b, 0x7b, 0xde, 0xfe, 0xa6, 0x4f, 0x16, 0x96,
	0x9e, 0xb8, 0x15, 0xf2, 0x14, 0xee, 0x09, 0x49, 0xc3, 0x04, 0x03, 0xa5, 0x69, 0x82, 0x1c, 0x95,
	0x0a, 0x12, 0x96, 0x32, 0x5d, 0x5f, 0xdf, 0xf3, 0xf6, 0x4b, 0xdd, 0xfb, 0xaf, 0x5e, 0x37, 0xef,
	0x3a, 0x7b, 0x2a, 0x3a, 0x6f, 0x33, 0xd1, 0x49, 0xa9, 0x1e, 0xb6, 0x8f, 0xb9, 0xf6, 0x6b, 0x8e,
	0x78, 0x3a, 0xe3, 0x9d, 0x18, 0x1a, 0x79, 0x0a, 0x3b, 0xc6, 0x45, 0x26, 0x59, 0x88, 0x41, 0x84,
	0x63, 0x66, 0x5f, 0x57, 0xdf, 0xb0, 0x6a, 0xcd, 0x57, 0xaf, 0x9b, 0x0f, 0xfe, 0xae, 0x76, 0x82,
	0x31, 0x0d, 0xa7, 0x3d, 0x0c, 0xfd, 0xed, 0x94, 0x4e, 0xfa, 0x86, 0xda, 0x9b, 0x31, 0xc9, 0xfb,
	0x70, 0x1b, 0x53, 0x94, 0x31, 0xf2, 0x70, 0x1a, 0x64, 0x74, 0xa4, 0xb0, 0x5e, 0xb4, 0x76, 0xaa,
	0xf3, 0x70, 0xdf, 0x44, 0xc9, 0x7b, 0x50, 0xcd, 0xad, 0xcc, 0x6c, 0xbf, 0x65, 0x71, 0x5b, 0x2e,
	0x9a, 0x3b, 0x6e, 0x7d, 0xe7, 0xc1, 0x3d, 0xbb, 0x3d, 0x3d, 0xcc, 0x84, 0x62, 0xfa, 0x4d, 0x29,
	0xc9, 0x87, 0x50, 0x54, 0xc8, 0x23, 0x94, 0x76, 0x77, 0x4a, 0xdd, 0xfa, 0xaf, 0x3f, 0x3e, 0xac,
	0xe5, 0x7b, 0x7b, 0x18, 0x45, 0x12, 0x95, 0x3a, 0xd5, 0x92, 0xf1, 0xd8, 0xcf, 0x71, 0xa4, 0x06,
	0x1b, 0x11, 0x72, 0x91, 0xda, 0xad, 0x29, 0xf9, 0xee, 0x81, 0x1c, 0x40, 0x91, 0xa6, 0x62, 0xc4,
	0xb5, 0x2d, 0xfc, 0x8d, 0x45, 0xcc, 0x81, 0xad, 0xef, 0x3d, 0x78, 0xdb, 0x66, 0xf5, 0x15, 0xd3,
	0xc3, 0x48, 0xd2, 0x8b, 0xff, 0x47, 0x5a, 0xbf, 0x78, 0x50, 0xb6, 0x69, 0x75, 0x85, 0x94, 0xe2,
	0x82, 0x7c, 0x0c, 0x9b, 0x03, 0xfb, 0x6f, 0x85, 0x64, 0xe6, 0xc8, 0x7f, 0x2d, 0x1d, 0xf2, 0x19,
	0x54, 0x39, 0x5e, 0x04, 0x5a, 0x68, 0x9a, 0x04, 0x11, 0x0e, 0x56, 0xe8, 0xd2, 0x0a, 0xc7, 0x8b,
	0x33, 0x83, 0xef, 0xe1, 0xc0, 0xfa, 0x01, 0xeb, 0xc7, 0xc7, 0x8c, 0x4e, 0xff, 0x6b, 0x3b, 0x9f,
	0x43, 0x55, 0x62, 0x4a, 0x19, 0x67, 0x3c, 0x5e, 0xd1, 0xce, 0xd6, 0x9c, 0x60, 0xfd, 0xbc, 0x28,
	0x40, 0xd5, 0xfa, 0x39, 0xc9, 0x8f, 0x36, 0x92, 0x47, 0x00, 0xb3, 0x73, 0x2e, 0x96, 0xbb, 0x5a,
	0xc0, 0x5e, 0xab, 0xc6, 0xad, 0x95, 0xab, 0xd1, 0x84, 0xb2, 0x34, 0xc5, 0x0c, 0x5c, 0x4d, 0xac,
	0x79, 0x1f, 0x6c, 0xa8, 0x67, 0x0b, 0xf3, 0x01, 0xdc, 0x59, 0x98, 0x69, 0x0e, 0x65, 0x7d, 0xfa,
	0xb7, 0xdf, 0xc4, 0x1d, 0xf4, 0x53, 0xa8, 0x38, 0xad, 0xbc, 0x92, 0x1b, 0xcb, 0xca, 0xe1, 0x5e,
	0x7d, 0xe8, 0xca, 0x79, 0x04, 0xdb, 0x0b, 0x2f, 0x52, 0xc8, 0xbe, 0xc5, 0xc8, 0xce, 0x8a, 0x1b,
	0x25, 0x16, 0x92, 0x3b, 0xb5, 0x14, 0x93, 0x85, 0x9d, 0xe4, 0xa1, 0x48, 0x82, 0xe7, 0x88, 0x76,
	0x8c, 0xdc, 0x9c, 0xc5, 0x0c, 0x7e, 0x84, 0xd8, 0xfa, 0x69, 0x3d, 0x1f, 0xff, 0x6e, 0xae, 0xcf,
	0xc6, 0xff, 0xbc, 0x69, 0xbc, 0xeb, 0x4d, 0x53, 0x48, 0xf4, 0x38, 0xaf, 0xf6, 0xd2, 0xe9, 0x68,
	0xb0, 0xe4, 0x0c, 0xee, 0x2e, 0x8e, 0x78, 0x3d, 0x94, 0xa8, 0x86, 0x22, 0x89, 0xf2, 0xb6, 0x5b,
	0x2a, 0x52, 0x5b, 0x60, 0x9f, 0xcd, 0xc8, 0xe4, 0x04, 0xb6, 0x17, 0x55, 0x07, 0x82, 0x8f, 0x54,
	0xde, 0x8d, 0x4b, 0x15, 0xef, 0x2c, 0x30, 0xbb, 0x86, 0x48, 0x8e, 0x4c, 0x63, 0x2b, 0x94, 0x63,
	0x0c, 0x9e, 0xd3, 0xd0, 0xf4, 0xe1, 0x8a, 0xf3, 0x7f, 0x2b, 0xa7, 0x1d, 0x59, 0x16, 0xe9, 0x42,
	0x25, 0x4c, 0x84, 0x9a, 0xab, 0x14, 0x57, 0x53, 0x29, 0x5b, 0x52, 0xae, 0xf1, 0x0e, 0x00, 0x53,
	0x7f, 0xf9, 0x24, 0x94, 0x98, 0x9a, 0x7d, 0x00, 0x1f, 0x01, 0xb8, 0x56, 0x0e, 0x42, 0x9a, 0xd5,
	0x37, 0x97, 0x6d, 0x75, 0xc9, 0x81, 0x1f, 0xd3, 0xcc, 0x30, 0xd5, 0x28, 0xcb, 0x92, 0xa9, 0x65,
	0x96, 0x96, 0x32, 0x1d, 0xd8, 0x30, 0x1f, 0x40, 0x49, 0x32, 0x75, 0x1e, 0x68, 0x86, 0xb2, 0x0e,
	0x7b, 0xde, 0xfe, 0x96, 0xbf, 0x69, 0x02, 0x67, 0x0c, 0x65, 0xeb, 0x37, 0x0f, 0x6a, 0xb6, 0x7f,
	0x8e, 0xb9, 0x46, 0x89, 0x4a, 0x1f, 0x86, 0xa1, 0x1c, 0xfd, 0x63, 0x07, 0x75, 0xa1, 0x92, 0xe7,
	0xcf, 0x78, 0x84, 0x93, 0x55, 0x5b, 0xa9, 0xec, 0x48, 0xc7, 0x86, 0x63, 0x34, 0x72, 0x27, 0x4e,
	0x63, 0xc5, 0x4e, 0x2a, 0x3b, 0x92, 0xd3, 0x78, 0x17, 0x2a, 0x83, 0x44, 0x84, 0xe7, 0xc1, 0x10,
	0x59, 0x3c, 0x74, 0x93, 0xac, 0xe0, 0x97, 0x6d, 0xec, 0x0b, 0x1b, 0xea, 0xf6, 0x7f, 0xbe, 0x6c,
	0x78, 0x2f, 0x2f, 0x1b, 0xde, 0x1f, 0x97, 0x0d, 0xef, 0xc5, 0x55, 0x63, 0xed, 0xe5, 0x55, 0x63,
	0xed, 0xf7, 0xab, 0xc6, 0xda, 0xd7, 0x9f, 0xc4, 0x4c, 0x0f, 0x47, 0x83, 0x76, 0x28, 0xd2, 0x8e,
	0xbd, 0x83, 0x89, 0x98, 0x85, 0x0f, 0x47, 0x9c, 0x8d, 0x51, 0x2a, 0xec, 0xcc, 0xef, 0x6d, 0x93,
	0xf9, 0xcd, 0x4d, 0x4f, 0x33, 0x54, 0x83, 0xa2, 0x3d, 0x78, 0x1f, 0xfd, 0x19, 0x00, 0x00, 0xff,
	0xff, 0x99, 0xc9, 0xa2, 0xc8, 0xda, 0x09, 0x00, 0x00,
}

func (m *EventParamsUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventParamsUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventParamsUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OracleEnabled {
		i--
		if m.OracleEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.EmergencyPause {
		i--
		if m.EmergencyPause {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.MaxPriceDeviation != nil {
		{
			size := m.MaxPriceDeviation.Size()
			i -= size
			if _, err := m.MaxPriceDeviation.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.OracleStalenessLimit != nil {
		{
			size := m.OracleStalenessLimit.Size()
			i -= size
			if _, err := m.OracleStalenessLimit.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.LiquidationEnabled {
		i--
		if m.LiquidationEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MaxCollateralAssetsPerUser != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.MaxCollateralAssetsPerUser))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxMarkets != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.MaxMarkets))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventDepositCollateral) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDepositCollateral) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDepositCollateral) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != nil {
		{
			size := m.Amount.Size()
			i -= size
			if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventWithdrawCollateral) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventWithdrawCollateral) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventWithdrawCollateral) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != nil {
		{
			size := m.Amount.Size()
			i -= size
			if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBorrow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBorrow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBorrow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewTotalDebt != nil {
		{
			size := m.NewTotalDebt.Size()
			i -= size
			if _, err := m.NewTotalDebt.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Amount != nil {
		{
			size := m.Amount.Size()
			i -= size
			if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Borrower) > 0 {
		i -= len(m.Borrower)
		copy(dAtA[i:], m.Borrower)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Borrower)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRepay) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRepay) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRepay) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RemainingDebt != nil {
		{
			size := m.RemainingDebt.Size()
			i -= size
			if _, err := m.RemainingDebt.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Amount != nil {
		{
			size := m.Amount.Size()
			i -= size
			if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Borrower) > 0 {
		i -= len(m.Borrower)
		copy(dAtA[i:], m.Borrower)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Borrower)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventLiquidate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventLiquidate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventLiquidate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProtocolFee != nil {
		{
			size := m.ProtocolFee.Size()
			i -= size
			if _, err := m.ProtocolFee.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.CollateralSeized != nil {
		{
			size := m.CollateralSeized.Size()
			i -= size
			if _, err := m.CollateralSeized.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.RepayAmount != nil {
		{
			size := m.RepayAmount.Size()
			i -= size
			if _, err := m.RepayAmount.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CollateralDenom) > 0 {
		i -= len(m.CollateralDenom)
		copy(dAtA[i:], m.CollateralDenom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.CollateralDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RepayDenom) > 0 {
		i -= len(m.RepayDenom)
		copy(dAtA[i:], m.RepayDenom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.RepayDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Borrower) > 0 {
		i -= len(m.Borrower)
		copy(dAtA[i:], m.Borrower)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Borrower)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Liquidator) > 0 {
		i -= len(m.Liquidator)
		copy(dAtA[i:], m.Liquidator)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Liquidator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventMarketUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMarketUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMarketUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RiskTier != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.RiskTier))
		i--
		dAtA[i] = 0x50
	}
	if m.SupplyCap != nil {
		{
			size := m.SupplyCap.Size()
			i -= size
			if _, err := m.SupplyCap.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.BorrowCap != nil {
		{
			size := m.BorrowCap.Size()
			i -= size
			if _, err := m.BorrowCap.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.IsEnabled {
		i--
		if m.IsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.CloseFactor != nil {
		{
			size := m.CloseFactor.Size()
			i -= size
			if _, err := m.CloseFactor.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.ReserveFactor != nil {
		{
			size := m.ReserveFactor.Size()
			i -= size
			if _, err := m.ReserveFactor.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.LiquidationBonus != nil {
		{
			size := m.LiquidationBonus.Size()
			i -= size
			if _, err := m.LiquidationBonus.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.LiquidationThreshold != nil {
		{
			size := m.LiquidationThreshold.Size()
			i -= size
			if _, err := m.LiquidationThreshold.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Ltv != nil {
		{
			size := m.Ltv.Size()
			i -= size
			if _, err := m.Ltv.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventInterestAccrued) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventInterestAccrued) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventInterestAccrued) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.SupplyIndex != nil {
		{
			size := m.SupplyIndex.Size()
			i -= size
			if _, err := m.SupplyIndex.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.BorrowIndex != nil {
		{
			size := m.BorrowIndex.Size()
			i -= size
			if _, err := m.BorrowIndex.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventParamsUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxMarkets != 0 {
		n += 1 + sovEvent(uint64(m.MaxMarkets))
	}
	if m.MaxCollateralAssetsPerUser != 0 {
		n += 1 + sovEvent(uint64(m.MaxCollateralAssetsPerUser))
	}
	if m.LiquidationEnabled {
		n += 2
	}
	if m.OracleStalenessLimit != nil {
		l = m.OracleStalenessLimit.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.MaxPriceDeviation != nil {
		l = m.MaxPriceDeviation.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.EmergencyPause {
		n += 2
	}
	if m.OracleEnabled {
		n += 2
	}
	return n
}

func (m *EventDepositCollateral) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventWithdrawCollateral) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventBorrow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Borrower)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.NewTotalDebt != nil {
		l = m.NewTotalDebt.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventRepay) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Borrower)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.RemainingDebt != nil {
		l = m.RemainingDebt.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventLiquidate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Liquidator)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Borrower)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.RepayDenom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.CollateralDenom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.RepayAmount != nil {
		l = m.RepayAmount.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.CollateralSeized != nil {
		l = m.CollateralSeized.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.ProtocolFee != nil {
		l = m.ProtocolFee.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventMarketUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Ltv != nil {
		l = m.Ltv.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.LiquidationThreshold != nil {
		l = m.LiquidationThreshold.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.LiquidationBonus != nil {
		l = m.LiquidationBonus.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.ReserveFactor != nil {
		l = m.ReserveFactor.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.CloseFactor != nil {
		l = m.CloseFactor.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.IsEnabled {
		n += 2
	}
	if m.BorrowCap != nil {
		l = m.BorrowCap.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.SupplyCap != nil {
		l = m.SupplyCap.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.RiskTier != 0 {
		n += 1 + sovEvent(uint64(m.RiskTier))
	}
	return n
}

func (m *EventInterestAccrued) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.BorrowIndex != nil {
		l = m.BorrowIndex.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.SupplyIndex != nil {
		l = m.SupplyIndex.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovEvent(uint64(m.BlockHeight))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventParamsUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventParamsUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventParamsUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMarkets", wireType)
			}
			m.MaxMarkets = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMarkets |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCollateralAssetsPerUser", wireType)
			}
			m.MaxCollateralAssetsPerUser = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCollateralAssetsPerUser |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LiquidationEnabled = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleStalenessLimit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.OracleStalenessLimit = &v
			if err := m.OracleStalenessLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPriceDeviation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.MaxPriceDeviation = &v
			if err := m.MaxPriceDeviation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyPause", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EmergencyPause = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OracleEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventDepositCollateral) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDepositCollateral: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDepositCollateral: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.Amount = &v
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventWithdrawCollateral) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventWithdrawCollateral: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventWithdrawCollateral: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.Amount = &v
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBorrow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBorrow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBorrow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Borrower = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.Amount = &v
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewTotalDebt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.NewTotalDebt = &v
			if err := m.NewTotalDebt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRepay) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRepay: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRepay: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Borrower = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.Amount = &v
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingDebt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.RemainingDebt = &v
			if err := m.RemainingDebt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventLiquidate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventLiquidate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventLiquidate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Liquidator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Liquidator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Borrower = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepayDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RepayDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepayAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.RepayAmount = &v
			if err := m.RepayAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralSeized", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.CollateralSeized = &v
			if err := m.CollateralSeized.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.ProtocolFee = &v
			if err := m.ProtocolFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventMarketUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMarketUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMarketUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltv", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.Ltv = &v
			if err := m.Ltv.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.LiquidationThreshold = &v
			if err := m.LiquidationThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationBonus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.LiquidationBonus = &v
			if err := m.LiquidationBonus.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.ReserveFactor = &v
			if err := m.ReserveFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CloseFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.CloseFactor = &v
			if err := m.CloseFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsEnabled = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.BorrowCap = &v
			if err := m.BorrowCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.SupplyCap = &v
			if err := m.SupplyCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RiskTier", wireType)
			}
			m.RiskTier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RiskTier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventInterestAccrued) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventInterestAccrued: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventInterestAccrued: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.BorrowIndex = &v
			if err := m.BorrowIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.SupplyIndex = &v
			if err := m.SupplyIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
