// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: overlend/lending/v1/lending.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ENUMS
type MarketType int32

const (
	MarketType_MARKET_TYPE_UNSPECIFIED MarketType = 0
	// semua asset collateral bisa digabung (cross-collateral)
	// punya ETH + ATOM, bisa pinjam berdasarkan total nilai keduanya
	MarketType_MARKET_TYPE_SHARED MarketType = 1
	// lebih ketat, risiko dibatasi.
	// satu collateral -> satu posisi pinjaman
	// deposit aset A → hanya bisa pinjam terhadap A itu saja
	MarketType_MARKET_TYPE_ISOLATED MarketType = 2
)

var MarketType_name = map[int32]string{
	0: "MARKET_TYPE_UNSPECIFIED",
	1: "MARKET_TYPE_SHARED",
	2: "MARKET_TYPE_ISOLATED",
}

var MarketType_value = map[string]int32{
	"MARKET_TYPE_UNSPECIFIED": 0,
	"MARKET_TYPE_SHARED":      1,
	"MARKET_TYPE_ISOLATED":    2,
}

func (x MarketType) String() string {
	return proto.EnumName(MarketType_name, int32(x))
}

func (MarketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_958abd5630583175, []int{0}
}

type OracleSourceType int32

const (
	OracleSourceType_ORACLE_SOURCE_UNSPECIFIED OracleSourceType = 0
	// harga rata-rata dalam periode waktu tertentu, biasanya dari DEX
	OracleSourceType_ORACLE_SOURCE_TWAP OracleSourceType = 1
	// harga dari Chainlink oracle
	OracleSourceType_ORACLE_SOURCE_CHAINLINK OracleSourceType = 2
)

var OracleSourceType_name = map[int32]string{
	0: "ORACLE_SOURCE_UNSPECIFIED",
	1: "ORACLE_SOURCE_TWAP",
	2: "ORACLE_SOURCE_CHAINLINK",
}

var OracleSourceType_value = map[string]int32{
	"ORACLE_SOURCE_UNSPECIFIED": 0,
	"ORACLE_SOURCE_TWAP":        1,
	"ORACLE_SOURCE_CHAINLINK":   2,
}

func (x OracleSourceType) String() string {
	return proto.EnumName(OracleSourceType_name, int32(x))
}

func (OracleSourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_958abd5630583175, []int{1}
}

// Market adlh konfigurasi utama (risk & parameter) untuk satu market lending per aset (denom).
type Market struct {
	// aset yang dipakai di market. Cth: "uusdc"
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// jenis market
	MarketType MarketType `protobuf:"varint,2,opt,name=market_type,json=marketType,proto3,enum=overlend.lending.v1.MarketType" json:"market_type,omitempty"`
	// seberapa besar user boleh pinjam dari collateral (persen)
	Ltv *cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=ltv,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"ltv,omitempty"`
	// batas aman sebelum kena likuidasi (persen)
	LiquidationThreshold *cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=liquidation_threshold,json=liquidationThreshold,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"liquidation_threshold,omitempty"`
	// bonus untuk liquidator (persen)
	LiquidationBonus *cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=liquidation_bonus,json=liquidationBonus,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"liquidation_bonus,omitempty"`
	// bagian bunga yang masuk ke protocol (bukan ke lender) (persen)
	ReserveFactor *cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=reserve_factor,json=reserveFactor,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"reserve_factor,omitempty"`
	// maksimal porsi utang yang bisa dilikuidasi sekaligus (persen)
	CloseFactor *cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=close_factor,json=closeFactor,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"close_factor,omitempty"`
	// batas total borrow di market ini
	BorrowCap *cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=borrow_cap,json=borrowCap,proto3,customtype=cosmossdk.io/math.Int" json:"borrow_cap,omitempty"`
	// batas total supply
	SupplyCap *cosmossdk_io_math.Int `protobuf:"bytes,9,opt,name=supply_cap,json=supplyCap,proto3,customtype=cosmossdk.io/math.Int" json:"supply_cap,omitempty"`
	// market aktif atau tidak
	IsEnabled bool `protobuf:"varint,10,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	// model bunga
	InterestModel *InterestRateModel `protobuf:"bytes,11,opt,name=interest_model,json=interestModel,proto3" json:"interest_model,omitempty"`
	// sumber harga aset (penting untuk LTV & liquidation)
	Oracle *OracleConfig `protobuf:"bytes,12,opt,name=oracle,proto3" json:"oracle,omitempty"`
	// level risiko aset
	RiskTier uint32 `protobuf:"varint,13,opt,name=risk_tier,json=riskTier,proto3" json:"risk_tier,omitempty"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_958abd5630583175, []int{0}
}
func (m *Market) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Market.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(m, src)
}
func (m *Market) XXX_Size() int {
	return m.Size()
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Market) GetMarketType() MarketType {
	if m != nil {
		return m.MarketType
	}
	return MarketType_MARKET_TYPE_UNSPECIFIED
}

func (m *Market) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

func (m *Market) GetInterestModel() *InterestRateModel {
	if m != nil {
		return m.InterestModel
	}
	return nil
}

func (m *Market) GetOracle() *OracleConfig {
	if m != nil {
		return m.Oracle
	}
	return nil
}

func (m *Market) GetRiskTier() uint32 {
	if m != nil {
		return m.RiskTier
	}
	return 0
}

// UserCollateral menyimpan data collateral (jaminan) yang disetor user untuk satu aset (denom)
type UserCollateral struct {
	// alamat user yang menyetor collateral
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// jenis aset yang dijadikan collateral
	Denom string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	// jumlah aset yang dijadikan collateral
	Amount *cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount,omitempty"`
}

func (m *UserCollateral) Reset()         { *m = UserCollateral{} }
func (m *UserCollateral) String() string { return proto.CompactTextString(m) }
func (*UserCollateral) ProtoMessage()    {}
func (*UserCollateral) Descriptor() ([]byte, []int) {
	return fileDescriptor_958abd5630583175, []int{1}
}
func (m *UserCollateral) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserCollateral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserCollateral.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserCollateral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCollateral.Merge(m, src)
}
func (m *UserCollateral) XXX_Size() int {
	return m.Size()
}
func (m *UserCollateral) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCollateral.DiscardUnknown(m)
}

var xxx_messageInfo_UserCollateral proto.InternalMessageInfo

func (m *UserCollateral) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *UserCollateral) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// UserDebt menyimpan state utang per user untuk satu aset (denom),
// dan dia pakai model berbasis index (bukan update bunga tiap waktu)
type UserDebt struct {
	// alamat user (borrower)
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// aset yang dipinjam. Cth: "uusdc"
	Denom string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	// Jumlah pokok utang saat terakhir dicatat. belum termasuk bunga terbaru
	Principal *cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=principal,proto3,customtype=cosmossdk.io/math.Int" json:"principal,omitempty"`
	// nilai borrow_index saat terakhir user berinteraksi
	InterestIndexSnapshot *cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=interest_index_snapshot,json=interestIndexSnapshot,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"interest_index_snapshot,omitempty"`
}

func (m *UserDebt) Reset()         { *m = UserDebt{} }
func (m *UserDebt) String() string { return proto.CompactTextString(m) }
func (*UserDebt) ProtoMessage()    {}
func (*UserDebt) Descriptor() ([]byte, []int) {
	return fileDescriptor_958abd5630583175, []int{2}
}
func (m *UserDebt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserDebt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserDebt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserDebt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDebt.Merge(m, src)
}
func (m *UserDebt) XXX_Size() int {
	return m.Size()
}
func (m *UserDebt) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDebt.DiscardUnknown(m)
}

var xxx_messageInfo_UserDebt proto.InternalMessageInfo

func (m *UserDebt) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *UserDebt) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// MarketState menyimpan state global (kondisi terkini)
// dari satu market lending untuk satu aset (denom)
type MarketState struct {
	// identitas aset market. Cth: "uusdc", "uatom"
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// Total semua dana yang disupply oleh lender
	TotalSupply *cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=total_supply,json=totalSupply,proto3,customtype=cosmossdk.io/math.Int" json:"total_supply,omitempty"`
	// total semua dana yang dipinjam
	TotalBorrow *cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=total_borrow,json=totalBorrow,proto3,customtype=cosmossdk.io/math.Int" json:"total_borrow,omitempty"`
	// index akumulasi bunga untuk borrower.
	// bukan langsung simpan bunga per user, tapi pakai index global
	BorrowIndex *cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=borrow_index,json=borrowIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"borrow_index,omitempty"`
	// index akumulasi bunga untuk lender. Mirip borrow_index tapi untuk yang deposit / supply
	// fungsi: menentukan berapa reward/lending yield user
	SupplyIndex *cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=supply_index,json=supplyIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"supply_index,omitempty"`
	// block terakhir state ini di-update
	LastUpdatedBlock int64 `protobuf:"varint,6,opt,name=last_updated_block,json=lastUpdatedBlock,proto3" json:"last_updated_block,omitempty"`
	// timestamp terakhir update
	LastUpdatedTime int64 `protobuf:"varint,7,opt,name=last_updated_time,json=lastUpdatedTime,proto3" json:"last_updated_time,omitempty"`
}

func (m *MarketState) Reset()         { *m = MarketState{} }
func (m *MarketState) String() string { return proto.CompactTextString(m) }
func (*MarketState) ProtoMessage()    {}
func (*MarketState) Descriptor() ([]byte, []int) {
	return fileDescriptor_958abd5630583175, []int{3}
}
func (m *MarketState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MarketState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MarketState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MarketState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketState.Merge(m, src)
}
func (m *MarketState) XXX_Size() int {
	return m.Size()
}
func (m *MarketState) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketState.DiscardUnknown(m)
}

var xxx_messageInfo_MarketState proto.InternalMessageInfo

func (m *MarketState) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MarketState) GetLastUpdatedBlock() int64 {
	if m != nil {
		return m.LastUpdatedBlock
	}
	return 0
}

func (m *MarketState) GetLastUpdatedTime() int64 {
	if m != nil {
		return m.LastUpdatedTime
	}
	return 0
}

// Interest = bunga pinjaman (biaya yang harus dibayar borrower, dan jadi pendapatan lender)
// InterestRateModel mendefinisikan parameter-parameter
// model suku bunga yang bersifat “kinked” (punya titik perubahan perilaku)
type InterestRateModel struct {
	// titik mulai bunga sebelum ada pengaruh utilisasi
	BaseRate *cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=base_rate,json=baseRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"base_rate,omitempty"`
	// laju kenaikan bunga di kondisi normal
	Slope1 *cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=slope1,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"slope1,omitempty"`
	// laju kenaikan bunga di kondisi high utilization (lebih agresif)
	Slope2 *cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=slope2,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"slope2,omitempty"`
	// titik perubahan laju peningkatan
	Kink *cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=kink,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"kink,omitempty"`
}

func (m *InterestRateModel) Reset()         { *m = InterestRateModel{} }
func (m *InterestRateModel) String() string { return proto.CompactTextString(m) }
func (*InterestRateModel) ProtoMessage()    {}
func (*InterestRateModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_958abd5630583175, []int{4}
}
func (m *InterestRateModel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InterestRateModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InterestRateModel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InterestRateModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterestRateModel.Merge(m, src)
}
func (m *InterestRateModel) XXX_Size() int {
	return m.Size()
}
func (m *InterestRateModel) XXX_DiscardUnknown() {
	xxx_messageInfo_InterestRateModel.DiscardUnknown(m)
}

var xxx_messageInfo_InterestRateModel proto.InternalMessageInfo

// OracleConfig mendefinisikan settingan Oracle
type OracleConfig struct {
	// sumber utama harga. Contoh: Chainlink, twap,
	PrimarySource OracleSourceType `protobuf:"varint,1,opt,name=primary_source,json=primarySource,proto3,enum=overlend.lending.v1.OracleSourceType" json:"primary_source,omitempty"`
	// sumber cadangan (fallback), dipakai kalau primary error
	SecondarySource OracleSourceType `protobuf:"varint,2,opt,name=secondary_source,json=secondarySource,proto3,enum=overlend.lending.v1.OracleSourceType" json:"secondary_source,omitempty"`
	// batas maksimal umur data
	MaxStaleness *cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=max_staleness,json=maxStaleness,proto3,customtype=cosmossdk.io/math.Int" json:"max_staleness,omitempty"`
	// batas selisih antara primary vs secondary
	MaxDeviation  *cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=max_deviation,json=maxDeviation,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"max_deviation,omitempty"`
	OracleEnabled bool                         `protobuf:"varint,5,opt,name=oracle_enabled,json=oracleEnabled,proto3" json:"oracle_enabled,omitempty"`
}

func (m *OracleConfig) Reset()         { *m = OracleConfig{} }
func (m *OracleConfig) String() string { return proto.CompactTextString(m) }
func (*OracleConfig) ProtoMessage()    {}
func (*OracleConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_958abd5630583175, []int{5}
}
func (m *OracleConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleConfig.Merge(m, src)
}
func (m *OracleConfig) XXX_Size() int {
	return m.Size()
}
func (m *OracleConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OracleConfig proto.InternalMessageInfo

func (m *OracleConfig) GetPrimarySource() OracleSourceType {
	if m != nil {
		return m.PrimarySource
	}
	return OracleSourceType_ORACLE_SOURCE_UNSPECIFIED
}

func (m *OracleConfig) GetSecondarySource() OracleSourceType {
	if m != nil {
		return m.SecondarySource
	}
	return OracleSourceType_ORACLE_SOURCE_UNSPECIFIED
}

func (m *OracleConfig) GetOracleEnabled() bool {
	if m != nil {
		return m.OracleEnabled
	}
	return false
}

func init() {
	proto.RegisterEnum("overlend.lending.v1.MarketType", MarketType_name, MarketType_value)
	proto.RegisterEnum("overlend.lending.v1.OracleSourceType", OracleSourceType_name, OracleSourceType_value)
	proto.RegisterType((*Market)(nil), "overlend.lending.v1.Market")
	proto.RegisterType((*UserCollateral)(nil), "overlend.lending.v1.UserCollateral")
	proto.RegisterType((*UserDebt)(nil), "overlend.lending.v1.UserDebt")
	proto.RegisterType((*MarketState)(nil), "overlend.lending.v1.MarketState")
	proto.RegisterType((*InterestRateModel)(nil), "overlend.lending.v1.InterestRateModel")
	proto.RegisterType((*OracleConfig)(nil), "overlend.lending.v1.OracleConfig")
}

func init() { proto.RegisterFile("overlend/lending/v1/lending.proto", fileDescriptor_958abd5630583175) }

var fileDescriptor_958abd5630583175 = []byte{
	// 1026 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0xcb, 0x6e, 0x1b, 0x37,
	0x17, 0xc7, 0x3d, 0x72, 0xac, 0x58, 0x47, 0x97, 0x28, 0xfc, 0x9c, 0x2f, 0x93, 0x04, 0x91, 0x1d,
	0x01, 0x29, 0x0c, 0xa3, 0x95, 0x20, 0x07, 0x68, 0x5a, 0x20, 0x28, 0xaa, 0x9b, 0x11, 0x21, 0xf2,
	0x05, 0x23, 0x19, 0x41, 0xdb, 0xc5, 0x80, 0x9a, 0xa1, 0x65, 0x42, 0x33, 0xc3, 0x29, 0x49, 0xa9,
	0xf6, 0xb2, 0x6f, 0xd0, 0xc7, 0xea, 0xa2, 0x8b, 0x2c, 0x8b, 0x14, 0x08, 0x0a, 0xfb, 0x25, 0xba,
	0x29, 0x50, 0x90, 0x1c, 0xc9, 0x72, 0xe3, 0x5a, 0xca, 0x46, 0x18, 0x1e, 0xfe, 0x7f, 0x7f, 0x92,
	0x22, 0xcf, 0x21, 0xe1, 0x19, 0x9b, 0x10, 0x1e, 0x90, 0xc8, 0xaf, 0xaa, 0x1f, 0x1a, 0x0d, 0xab,
	0x93, 0xda, 0xf4, 0xb3, 0x12, 0x73, 0x26, 0x19, 0xfa, 0xdf, 0x54, 0x52, 0x99, 0xc6, 0x27, 0xb5,
	0xc7, 0x25, 0x8f, 0x89, 0x90, 0x89, 0xea, 0x00, 0x0b, 0x52, 0x9d, 0xd4, 0x06, 0x44, 0xe2, 0x5a,
	0xd5, 0x63, 0x34, 0x32, 0xd0, 0xe3, 0x8d, 0x21, 0x1b, 0x32, 0xfd, 0x59, 0x55, 0x5f, 0x49, 0xf4,
	0x91, 0xa1, 0x5c, 0xd3, 0x61, 0x1a, 0xa6, 0xab, 0xfc, 0xf7, 0x1a, 0xa4, 0xf7, 0x31, 0x1f, 0x11,
	0x89, 0x36, 0x60, 0xcd, 0x27, 0x11, 0x0b, 0x6d, 0x6b, 0xcb, 0xda, 0xce, 0x38, 0xa6, 0x81, 0xbe,
	0x85, 0x6c, 0xa8, 0xfb, 0x5d, 0x79, 0x1e, 0x13, 0x3b, 0xb5, 0x65, 0x6d, 0x17, 0x76, 0x37, 0x2b,
	0x37, 0x4c, 0xae, 0x62, 0x7c, 0xfa, 0xe7, 0x31, 0x71, 0x20, 0x9c, 0x7d, 0xa3, 0x1a, 0xac, 0x06,
	0x72, 0x62, 0xaf, 0x2a, 0xd7, 0xc6, 0xe6, 0xfb, 0x0f, 0x9b, 0x4f, 0xcc, 0x0c, 0x84, 0x3f, 0xaa,
	0x50, 0x56, 0x0d, 0xb1, 0x3c, 0xad, 0x74, 0xc9, 0x10, 0x7b, 0xe7, 0x2d, 0xe2, 0x39, 0x4a, 0x8b,
	0xfa, 0xf0, 0x20, 0xa0, 0x3f, 0x8e, 0xa9, 0x8f, 0x25, 0x65, 0x91, 0x2b, 0x4f, 0x39, 0x11, 0xa7,
	0x2c, 0xf0, 0xed, 0x3b, 0xcb, 0x99, 0x6c, 0xcc, 0xd1, 0xfd, 0x29, 0x8c, 0xba, 0x70, 0x7f, 0xde,
	0x75, 0xc0, 0xa2, 0xb1, 0xb0, 0xd7, 0x96, 0x73, 0x2c, 0xce, 0x91, 0x0d, 0x05, 0xa2, 0x3d, 0x28,
	0x70, 0x22, 0x08, 0x9f, 0x10, 0xf7, 0x04, 0x7b, 0x92, 0x71, 0x3b, 0xbd, 0x9c, 0x55, 0x3e, 0xc1,
	0xf6, 0x34, 0x85, 0x1a, 0x90, 0xf3, 0x02, 0x26, 0x66, 0x2e, 0x77, 0x97, 0x73, 0xc9, 0x6a, 0x28,
	0xf1, 0xf8, 0x0a, 0x60, 0xc0, 0x38, 0x67, 0x3f, 0xb9, 0x1e, 0x8e, 0xed, 0x75, 0xed, 0xf0, 0xe8,
	0xfd, 0x87, 0xcd, 0x07, 0x1f, 0x3b, 0x74, 0x22, 0xe9, 0x64, 0x8c, 0xb8, 0x89, 0x63, 0x45, 0x8a,
	0x71, 0x1c, 0x07, 0xe7, 0x9a, 0xcc, 0x2c, 0x24, 0x8d, 0x58, 0x91, 0x4f, 0x01, 0xa8, 0x70, 0x49,
	0x84, 0x07, 0x01, 0xf1, 0x6d, 0xd8, 0xb2, 0xb6, 0xd7, 0x9d, 0x0c, 0x15, 0x6d, 0x13, 0x40, 0xfb,
	0x50, 0xa0, 0x91, 0x24, 0x9c, 0x08, 0xe9, 0x86, 0xcc, 0x27, 0x81, 0x9d, 0xdd, 0xb2, 0xb6, 0xb3,
	0xbb, 0x9f, 0xdd, 0x78, 0x74, 0x3a, 0x89, 0xd4, 0xc1, 0x92, 0xec, 0x2b, 0xb5, 0x93, 0x9f, 0xd2,
	0xba, 0x89, 0xbe, 0x86, 0x34, 0xe3, 0xd8, 0x0b, 0x88, 0x9d, 0xd3, 0x36, 0xcf, 0x6e, 0xb4, 0x39,
	0xd4, 0x92, 0x26, 0x8b, 0x4e, 0xe8, 0xd0, 0x49, 0x00, 0xf4, 0x04, 0x32, 0x9c, 0x8a, 0x91, 0x2b,
	0x29, 0xe1, 0x76, 0x7e, 0xcb, 0xda, 0xce, 0x3b, 0xeb, 0x2a, 0xd0, 0xa7, 0x84, 0x97, 0x05, 0x14,
	0x8e, 0x05, 0xe1, 0x4d, 0x16, 0x04, 0x58, 0x12, 0x8e, 0x03, 0x64, 0xc3, 0x5d, 0xec, 0xfb, 0x9c,
	0x08, 0xa1, 0x13, 0x21, 0xe7, 0x4c, 0x9b, 0x57, 0x09, 0x92, 0x9a, 0x4f, 0x90, 0x1a, 0xa4, 0x71,
	0xc8, 0xc6, 0x91, 0x4c, 0x4e, 0xf8, 0x2d, 0xff, 0x5e, 0x22, 0x2c, 0xff, 0x66, 0xc1, 0xba, 0x1a,
	0xb5, 0x45, 0x06, 0xf2, 0x93, 0xc7, 0x7b, 0x09, 0x99, 0x98, 0xd3, 0xc8, 0xa3, 0x31, 0x0e, 0x16,
	0x0f, 0x79, 0xa5, 0x45, 0x6f, 0xe1, 0xe1, 0x6c, 0x47, 0x68, 0xe4, 0x93, 0x33, 0x57, 0x44, 0x38,
	0x16, 0xa7, 0x4c, 0x2e, 0x9b, 0x56, 0x0f, 0xa6, 0x7c, 0x47, 0xe1, 0xbd, 0x84, 0x2e, 0xff, 0xbc,
	0x0a, 0x59, 0x93, 0xfb, 0x3d, 0x89, 0x25, 0xf9, 0x8f, 0x42, 0xf2, 0x0a, 0x72, 0x92, 0x49, 0x1c,
	0xb8, 0xe6, 0x08, 0x99, 0x45, 0xdd, 0x36, 0xf5, 0xac, 0x96, 0xf7, 0xb4, 0xfa, 0x8a, 0x36, 0x47,
	0x77, 0xf1, 0xc2, 0x0d, 0xdd, 0xd0, 0x6a, 0x95, 0x63, 0x49, 0x7e, 0xe8, 0x85, 0x2f, 0xbb, 0xde,
	0xac, 0x81, 0xf4, 0x6a, 0x95, 0x47, 0x92, 0x29, 0xc6, 0x63, 0xc9, 0xc2, 0x91, 0x35, 0x90, 0xf1,
	0xf8, 0x1c, 0x50, 0x80, 0x85, 0x74, 0xc7, 0xb1, 0x8f, 0x25, 0xf1, 0xdd, 0x41, 0xc0, 0xbc, 0x91,
	0xae, 0x1b, 0xab, 0x4e, 0x51, 0xf5, 0x1c, 0x9b, 0x8e, 0x86, 0x8a, 0xa3, 0x1d, 0xb8, 0x7f, 0x4d,
	0x2d, 0x69, 0x48, 0x74, 0x79, 0x58, 0x75, 0xee, 0xcd, 0x89, 0xfb, 0x34, 0x24, 0xe5, 0xbf, 0x2c,
	0xb8, 0xff, 0x51, 0x12, 0xa1, 0x57, 0x90, 0x51, 0x37, 0x85, 0xcb, 0xb1, 0x24, 0x66, 0x37, 0x16,
	0x4f, 0x78, 0x5d, 0x11, 0xca, 0x02, 0xbd, 0x84, 0xb4, 0x08, 0x58, 0x4c, 0x6a, 0xc9, 0x5e, 0x2d,
	0x44, 0x13, 0xf9, 0x0c, 0xdc, 0x5d, 0xb6, 0xe8, 0x27, 0x72, 0xf4, 0x02, 0xee, 0x8c, 0x68, 0x34,
	0x5a, 0x76, 0x7f, 0xb4, 0xb8, 0xfc, 0x47, 0x0a, 0x72, 0xf3, 0x89, 0x8f, 0xba, 0x50, 0x88, 0x39,
	0x0d, 0x31, 0x3f, 0x77, 0x05, 0x1b, 0x73, 0xcf, 0x2c, 0xbd, 0xb0, 0xfb, 0xfc, 0x96, 0x9a, 0xd1,
	0xd3, 0x42, 0x7d, 0x77, 0xe5, 0x13, 0xd8, 0x84, 0xd0, 0x11, 0x14, 0x05, 0xf1, 0x58, 0xe4, 0xcf,
	0xf9, 0xa5, 0x3e, 0xc5, 0xef, 0xde, 0x0c, 0x4f, 0x1c, 0xbf, 0x81, 0x7c, 0x88, 0xcf, 0x5c, 0x21,
	0x71, 0x40, 0x22, 0x95, 0xf7, 0x0b, 0x0f, 0x73, 0x2e, 0xc4, 0x67, 0xbd, 0xa9, 0x1c, 0xb5, 0x0c,
	0xef, 0x93, 0x09, 0xd5, 0xf7, 0xd1, 0xb2, 0x7f, 0x97, 0x72, 0x69, 0x4d, 0x21, 0xf4, 0x1c, 0x0a,
	0xa6, 0x40, 0xce, 0x6a, 0xf8, 0x9a, 0xae, 0xe1, 0x79, 0x13, 0x4d, 0xea, 0xf8, 0xce, 0x0f, 0x00,
	0x57, 0xf7, 0x3a, 0x7a, 0x02, 0x0f, 0xf7, 0xeb, 0xce, 0x9b, 0x76, 0xdf, 0xed, 0x7f, 0x77, 0xd4,
	0x76, 0x8f, 0x0f, 0x7a, 0x47, 0xed, 0x66, 0x67, 0xaf, 0xd3, 0x6e, 0x15, 0x57, 0xd0, 0xff, 0x01,
	0xcd, 0x77, 0xf6, 0x5e, 0xd7, 0x9d, 0x76, 0xab, 0x68, 0x21, 0x1b, 0x36, 0xe6, 0xe3, 0x9d, 0xde,
	0x61, 0xb7, 0xde, 0x6f, 0xb7, 0x8a, 0xa9, 0x9d, 0x13, 0x28, 0xfe, 0xfb, 0xef, 0x42, 0x4f, 0xe1,
	0xd1, 0xa1, 0x53, 0x6f, 0x76, 0xdb, 0x6e, 0xef, 0xf0, 0xd8, 0x69, 0xde, 0x30, 0xc8, 0xf5, 0xee,
	0xfe, 0xdb, 0xfa, 0x51, 0xd1, 0x52, 0x33, 0xbb, 0x1e, 0x6f, 0xbe, 0xae, 0x77, 0x0e, 0xba, 0x9d,
	0x83, 0x37, 0xc5, 0x54, 0xe3, 0xe8, 0xd7, 0x8b, 0x92, 0xf5, 0xee, 0xa2, 0x64, 0xfd, 0x79, 0x51,
	0xb2, 0x7e, 0xb9, 0x2c, 0xad, 0xbc, 0xbb, 0x2c, 0xad, 0xfc, 0x7e, 0x59, 0x5a, 0xf9, 0xfe, 0xcb,
	0x21, 0x95, 0xa7, 0xe3, 0x41, 0xc5, 0x63, 0x61, 0x55, 0xef, 0x26, 0x1b, 0x52, 0xef, 0x8b, 0x71,
	0x44, 0x27, 0x84, 0x0b, 0x52, 0x9d, 0x3d, 0xd3, 0xce, 0x66, 0x0f, 0x35, 0xf5, 0x0c, 0x12, 0x83,
	0xb4, 0x7e, 0x3e, 0xbd, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xf3, 0x12, 0x5e, 0xc9, 0x09,
	0x00, 0x00,
}

func (m *Market) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Market) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Market) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RiskTier != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.RiskTier))
		i--
		dAtA[i] = 0x68
	}
	if m.Oracle != nil {
		{
			size, err := m.Oracle.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	if m.InterestModel != nil {
		{
			size, err := m.InterestModel.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if m.IsEnabled {
		i--
		if m.IsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.SupplyCap != nil {
		{
			size := m.SupplyCap.Size()
			i -= size
			if _, err := m.SupplyCap.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.BorrowCap != nil {
		{
			size := m.BorrowCap.Size()
			i -= size
			if _, err := m.BorrowCap.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.CloseFactor != nil {
		{
			size := m.CloseFactor.Size()
			i -= size
			if _, err := m.CloseFactor.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.ReserveFactor != nil {
		{
			size := m.ReserveFactor.Size()
			i -= size
			if _, err := m.ReserveFactor.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.LiquidationBonus != nil {
		{
			size := m.LiquidationBonus.Size()
			i -= size
			if _, err := m.LiquidationBonus.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.LiquidationThreshold != nil {
		{
			size := m.LiquidationThreshold.Size()
			i -= size
			if _, err := m.LiquidationThreshold.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Ltv != nil {
		{
			size := m.Ltv.Size()
			i -= size
			if _, err := m.Ltv.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.MarketType != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.MarketType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintLending(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UserCollateral) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserCollateral) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserCollateral) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != nil {
		{
			size := m.Amount.Size()
			i -= size
			if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintLending(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintLending(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UserDebt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserDebt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserDebt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InterestIndexSnapshot != nil {
		{
			size := m.InterestIndexSnapshot.Size()
			i -= size
			if _, err := m.InterestIndexSnapshot.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Principal != nil {
		{
			size := m.Principal.Size()
			i -= size
			if _, err := m.Principal.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintLending(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintLending(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MarketState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MarketState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MarketState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUpdatedTime != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.LastUpdatedTime))
		i--
		dAtA[i] = 0x38
	}
	if m.LastUpdatedBlock != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.LastUpdatedBlock))
		i--
		dAtA[i] = 0x30
	}
	if m.SupplyIndex != nil {
		{
			size := m.SupplyIndex.Size()
			i -= size
			if _, err := m.SupplyIndex.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.BorrowIndex != nil {
		{
			size := m.BorrowIndex.Size()
			i -= size
			if _, err := m.BorrowIndex.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.TotalBorrow != nil {
		{
			size := m.TotalBorrow.Size()
			i -= size
			if _, err := m.TotalBorrow.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.TotalSupply != nil {
		{
			size := m.TotalSupply.Size()
			i -= size
			if _, err := m.TotalSupply.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintLending(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InterestRateModel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InterestRateModel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InterestRateModel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Kink != nil {
		{
			size := m.Kink.Size()
			i -= size
			if _, err := m.Kink.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Slope2 != nil {
		{
			size := m.Slope2.Size()
			i -= size
			if _, err := m.Slope2.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Slope1 != nil {
		{
			size := m.Slope1.Size()
			i -= size
			if _, err := m.Slope1.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.BaseRate != nil {
		{
			size := m.BaseRate.Size()
			i -= size
			if _, err := m.BaseRate.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OracleConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OracleEnabled {
		i--
		if m.OracleEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.MaxDeviation != nil {
		{
			size := m.MaxDeviation.Size()
			i -= size
			if _, err := m.MaxDeviation.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.MaxStaleness != nil {
		{
			size := m.MaxStaleness.Size()
			i -= size
			if _, err := m.MaxStaleness.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.SecondarySource != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.SecondarySource))
		i--
		dAtA[i] = 0x10
	}
	if m.PrimarySource != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.PrimarySource))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLending(dAtA []byte, offset int, v uint64) int {
	offset -= sovLending(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Market) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	if m.MarketType != 0 {
		n += 1 + sovLending(uint64(m.MarketType))
	}
	if m.Ltv != nil {
		l = m.Ltv.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.LiquidationThreshold != nil {
		l = m.LiquidationThreshold.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.LiquidationBonus != nil {
		l = m.LiquidationBonus.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.ReserveFactor != nil {
		l = m.ReserveFactor.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.CloseFactor != nil {
		l = m.CloseFactor.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.BorrowCap != nil {
		l = m.BorrowCap.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.SupplyCap != nil {
		l = m.SupplyCap.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.IsEnabled {
		n += 2
	}
	if m.InterestModel != nil {
		l = m.InterestModel.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.Oracle != nil {
		l = m.Oracle.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.RiskTier != 0 {
		n += 1 + sovLending(uint64(m.RiskTier))
	}
	return n
}

func (m *UserCollateral) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	return n
}

func (m *UserDebt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	if m.Principal != nil {
		l = m.Principal.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.InterestIndexSnapshot != nil {
		l = m.InterestIndexSnapshot.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	return n
}

func (m *MarketState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	if m.TotalSupply != nil {
		l = m.TotalSupply.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.TotalBorrow != nil {
		l = m.TotalBorrow.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.BorrowIndex != nil {
		l = m.BorrowIndex.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.SupplyIndex != nil {
		l = m.SupplyIndex.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.LastUpdatedBlock != 0 {
		n += 1 + sovLending(uint64(m.LastUpdatedBlock))
	}
	if m.LastUpdatedTime != 0 {
		n += 1 + sovLending(uint64(m.LastUpdatedTime))
	}
	return n
}

func (m *InterestRateModel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BaseRate != nil {
		l = m.BaseRate.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.Slope1 != nil {
		l = m.Slope1.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.Slope2 != nil {
		l = m.Slope2.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.Kink != nil {
		l = m.Kink.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	return n
}

func (m *OracleConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PrimarySource != 0 {
		n += 1 + sovLending(uint64(m.PrimarySource))
	}
	if m.SecondarySource != 0 {
		n += 1 + sovLending(uint64(m.SecondarySource))
	}
	if m.MaxStaleness != nil {
		l = m.MaxStaleness.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.MaxDeviation != nil {
		l = m.MaxDeviation.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.OracleEnabled {
		n += 2
	}
	return n
}

func sovLending(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLending(x uint64) (n int) {
	return sovLending(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Market) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Market: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Market: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketType", wireType)
			}
			m.MarketType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketType |= MarketType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltv", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.Ltv = &v
			if err := m.Ltv.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.LiquidationThreshold = &v
			if err := m.LiquidationThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationBonus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.LiquidationBonus = &v
			if err := m.LiquidationBonus.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.ReserveFactor = &v
			if err := m.ReserveFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CloseFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.CloseFactor = &v
			if err := m.CloseFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.BorrowCap = &v
			if err := m.BorrowCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.SupplyCap = &v
			if err := m.SupplyCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsEnabled = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterestModel", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.InterestModel == nil {
				m.InterestModel = &InterestRateModel{}
			}
			if err := m.InterestModel.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Oracle", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Oracle == nil {
				m.Oracle = &OracleConfig{}
			}
			if err := m.Oracle.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RiskTier", wireType)
			}
			m.RiskTier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RiskTier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserCollateral) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserCollateral: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserCollateral: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.Amount = &v
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserDebt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserDebt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserDebt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Principal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.Principal = &v
			if err := m.Principal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterestIndexSnapshot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.InterestIndexSnapshot = &v
			if err := m.InterestIndexSnapshot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MarketState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MarketState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MarketState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.TotalSupply = &v
			if err := m.TotalSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBorrow", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.TotalBorrow = &v
			if err := m.TotalBorrow.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.BorrowIndex = &v
			if err := m.BorrowIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.SupplyIndex = &v
			if err := m.SupplyIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdatedBlock", wireType)
			}
			m.LastUpdatedBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdatedBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdatedTime", wireType)
			}
			m.LastUpdatedTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdatedTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InterestRateModel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InterestRateModel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InterestRateModel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.BaseRate = &v
			if err := m.BaseRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slope1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.Slope1 = &v
			if err := m.Slope1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slope2", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.Slope2 = &v
			if err := m.Slope2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kink", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.Kink = &v
			if err := m.Kink.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OracleConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrimarySource", wireType)
			}
			m.PrimarySource = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrimarySource |= OracleSourceType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecondarySource", wireType)
			}
			m.SecondarySource = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecondarySource |= OracleSourceType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxStaleness", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.MaxStaleness = &v
			if err := m.MaxStaleness.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDeviation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.MaxDeviation = &v
			if err := m.MaxDeviation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OracleEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipLending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLending(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLending
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLending
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLending
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLending
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLending
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLending
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLending        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLending          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLending = fmt.Errorf("proto: unexpected end of group")
)
