// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: overlend/lending/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines global module parameters
type Params struct {
	// jumlah maksimal market yang boleh ada di sistem
	MaxMarkets uint64 `protobuf:"varint,1,opt,name=max_markets,json=maxMarkets,proto3" json:"max_markets,omitempty"`
	// maksimal jumlah jenis collateral per user
	MaxCollateralAssetsPerUser uint64 `protobuf:"varint,2,opt,name=max_collateral_assets_per_user,json=maxCollateralAssetsPerUser,proto3" json:"max_collateral_assets_per_user,omitempty"`
	// apakah fitur likuidasi aktif
	LiquidationEnabled bool `protobuf:"varint,3,opt,name=liquidation_enabled,json=liquidationEnabled,proto3" json:"liquidation_enabled,omitempty"`
	// batas global umur data harga
	OracleStalenessLimit *cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=oracle_staleness_limit,json=oracleStalenessLimit,proto3,customtype=cosmossdk.io/math.Int" json:"oracle_staleness_limit,omitempty"`
	// batas selisih harga maksimum yang diterima
	MaxPriceDeviation *cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=max_price_deviation,json=maxPriceDeviation,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"max_price_deviation,omitempty"`
	// kill switch seluruh protocol
	EmergencyPause bool `protobuf:"varint,6,opt,name=emergency_pause,json=emergencyPause,proto3" json:"emergency_pause,omitempty"`
	// apakah oracle aktif
	OracleEnabled bool `protobuf:"varint,7,opt,name=oracle_enabled,json=oracleEnabled,proto3" json:"oracle_enabled,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6baf883664abd796, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxMarkets() uint64 {
	if m != nil {
		return m.MaxMarkets
	}
	return 0
}

func (m *Params) GetMaxCollateralAssetsPerUser() uint64 {
	if m != nil {
		return m.MaxCollateralAssetsPerUser
	}
	return 0
}

func (m *Params) GetLiquidationEnabled() bool {
	if m != nil {
		return m.LiquidationEnabled
	}
	return false
}

func (m *Params) GetEmergencyPause() bool {
	if m != nil {
		return m.EmergencyPause
	}
	return false
}

func (m *Params) GetOracleEnabled() bool {
	if m != nil {
		return m.OracleEnabled
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "overlend.lending.v1.Params")
}

func init() { proto.RegisterFile("overlend/lending/v1/params.proto", fileDescriptor_6baf883664abd796) }

var fileDescriptor_6baf883664abd796 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xc1, 0x6b, 0xd4, 0x40,
	0x14, 0xc6, 0x37, 0xb6, 0xae, 0x3a, 0x62, 0xc5, 0xd9, 0x2a, 0xe9, 0x0a, 0xd9, 0x45, 0x10, 0xf7,
	0x62, 0x42, 0x11, 0xbc, 0xbb, 0xd6, 0x83, 0x50, 0x69, 0x58, 0xf1, 0xe2, 0x65, 0x78, 0x3b, 0x79,
	0xa4, 0x43, 0x67, 0x32, 0x71, 0x66, 0x12, 0xb2, 0xff, 0x45, 0xff, 0x2c, 0x8f, 0x3d, 0x4a, 0x0f,
	0x45, 0x76, 0xff, 0x11, 0xc9, 0xcc, 0xee, 0x22, 0xf4, 0x12, 0x92, 0xef, 0xfb, 0x7d, 0x2f, 0x7c,
	0xbc, 0x47, 0xa6, 0xba, 0x45, 0x23, 0xb1, 0x2a, 0xb2, 0xfe, 0x21, 0xaa, 0x32, 0x6b, 0x4f, 0xb3,
	0x1a, 0x0c, 0x28, 0x9b, 0xd6, 0x46, 0x3b, 0x4d, 0x47, 0x3b, 0x22, 0xdd, 0x12, 0x69, 0x7b, 0x3a,
	0x3e, 0x2e, 0x75, 0xa9, 0xbd, 0x9f, 0xf5, 0x6f, 0x01, 0x1d, 0x9f, 0x70, 0x6d, 0x95, 0xb6, 0x2c,
	0x18, 0xe1, 0x23, 0x58, 0x6f, 0xae, 0x0f, 0xc8, 0x30, 0xf7, 0x63, 0xe9, 0x84, 0x3c, 0x55, 0xd0,
	0x31, 0x05, 0xe6, 0x0a, 0x9d, 0x8d, 0xa3, 0x69, 0x34, 0x3b, 0x5c, 0x10, 0x05, 0xdd, 0xb7, 0xa0,
	0xd0, 0x39, 0x49, 0x7a, 0x80, 0x6b, 0x29, 0xc1, 0xa1, 0x01, 0xc9, 0xc0, 0x5a, 0x74, 0x96, 0xd5,
	0x68, 0x58, 0x63, 0xd1, 0xc4, 0x0f, 0x7c, 0x66, 0xac, 0xa0, 0xfb, 0xbc, 0x87, 0x3e, 0x79, 0x26,
	0x47, 0xf3, 0xc3, 0xa2, 0xa1, 0x19, 0x19, 0x49, 0xf1, 0xab, 0x11, 0x05, 0x38, 0xa1, 0x2b, 0x86,
	0x15, 0x2c, 0x25, 0x16, 0xf1, 0xc1, 0x34, 0x9a, 0x3d, 0x5e, 0xd0, 0xff, 0xac, 0x2f, 0xc1, 0xa1,
	0x17, 0xe4, 0x95, 0x36, 0xc0, 0x25, 0x32, 0xeb, 0x40, 0x62, 0x85, 0xd6, 0x32, 0x29, 0x94, 0x70,
	0xf1, 0xe1, 0x34, 0x9a, 0x3d, 0x99, 0x9f, 0xdc, 0xde, 0x4d, 0x5e, 0x86, 0x4a, 0xb6, 0xb8, 0x4a,
	0x85, 0xce, 0x14, 0xb8, 0xcb, 0xf4, 0x6b, 0xe5, 0x16, 0xc7, 0x21, 0xf8, 0x7d, 0x97, 0x3b, 0xef,
	0x63, 0xf4, 0x82, 0x8c, 0xfa, 0x16, 0xb5, 0x11, 0x1c, 0x59, 0x81, 0xad, 0xf0, 0xbf, 0x8b, 0x1f,
	0xfa, 0x69, 0x93, 0xdb, 0xbb, 0xc9, 0xeb, 0xfb, 0xd3, 0xce, 0xb1, 0x04, 0xbe, 0x3a, 0x43, 0xbe,
	0x78, 0xa1, 0xa0, 0xcb, 0xfb, 0xe8, 0xd9, 0x2e, 0x49, 0xdf, 0x91, 0xe7, 0xa8, 0xd0, 0x94, 0x58,
	0xf1, 0x15, 0xab, 0xa1, 0xb1, 0x18, 0x0f, 0x7d, 0x9d, 0xa3, 0xbd, 0x9c, 0xf7, 0x2a, 0x7d, 0x4b,
	0x8e, 0xb6, 0x55, 0x76, 0xb5, 0x1f, 0x79, 0xee, 0x59, 0x50, 0xb7, 0x8d, 0xe7, 0xf9, 0xef, 0x75,
	0x12, 0xdd, 0xac, 0x93, 0xe8, 0xef, 0x3a, 0x89, 0xae, 0x37, 0xc9, 0xe0, 0x66, 0x93, 0x0c, 0xfe,
	0x6c, 0x92, 0xc1, 0xcf, 0x8f, 0xa5, 0x70, 0x97, 0xcd, 0x32, 0xe5, 0x5a, 0x65, 0x7e, 0xfb, 0xba,
	0x14, 0xfc, 0x7d, 0x53, 0x89, 0x16, 0x8d, 0xc5, 0x6c, 0x7f, 0x32, 0xdd, 0xfe, 0x68, 0xdc, 0xaa,
	0x46, 0xbb, 0x1c, 0xfa, 0x5d, 0x7f, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x9e, 0x6e, 0xda,
	0x55, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OracleEnabled {
		i--
		if m.OracleEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.EmergencyPause {
		i--
		if m.EmergencyPause {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.MaxPriceDeviation != nil {
		{
			size := m.MaxPriceDeviation.Size()
			i -= size
			if _, err := m.MaxPriceDeviation.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.OracleStalenessLimit != nil {
		{
			size := m.OracleStalenessLimit.Size()
			i -= size
			if _, err := m.OracleStalenessLimit.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.LiquidationEnabled {
		i--
		if m.LiquidationEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MaxCollateralAssetsPerUser != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxCollateralAssetsPerUser))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxMarkets != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxMarkets))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxMarkets != 0 {
		n += 1 + sovParams(uint64(m.MaxMarkets))
	}
	if m.MaxCollateralAssetsPerUser != 0 {
		n += 1 + sovParams(uint64(m.MaxCollateralAssetsPerUser))
	}
	if m.LiquidationEnabled {
		n += 2
	}
	if m.OracleStalenessLimit != nil {
		l = m.OracleStalenessLimit.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MaxPriceDeviation != nil {
		l = m.MaxPriceDeviation.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	if m.EmergencyPause {
		n += 2
	}
	if m.OracleEnabled {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMarkets", wireType)
			}
			m.MaxMarkets = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMarkets |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCollateralAssetsPerUser", wireType)
			}
			m.MaxCollateralAssetsPerUser = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCollateralAssetsPerUser |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LiquidationEnabled = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleStalenessLimit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.OracleStalenessLimit = &v
			if err := m.OracleStalenessLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPriceDeviation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.LegacyDec
			m.MaxPriceDeviation = &v
			if err := m.MaxPriceDeviation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyPause", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EmergencyPause = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OracleEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
